# Numpy

In [386]:
import numpy as np

# 배열

## sequence 데이터로부터 배열 생성

#### range 배열 생성

In [387]:
data1 = range(10)
arr1 = np.array(data1)

arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### list 배열 생성
##### \*\*\* python 내장 List와 다르게 numpy 배열은  type을 통일시킴

In [388]:
data2 = [0.1, 5, 4, 12, 0.5]
arr2 = np.array(data2)

arr2 # 모두 실수로 변환


array([ 0.1,  5. ,  4. , 12. ,  0.5])

#### list 배열 생성 with random

In [389]:
import random

# random.uniform = a<=N<=b 사이에 균등분포 랜덤
data3 = [random.uniform(-1, 1) for i in range(10)] # List Comprehension
arr3 = np.array(data3)
arr3

array([ 0.66938351, -0.29119613, -0.2911237 , -0.44152411, -0.85054693,
        0.31250691, -0.93707938,  0.51186031, -0.8807393 ,  0.10914853])

#### 속성혼합

In [390]:
# 혼합시 포함관계로
arr4 = np.array([1, 2, 'a', 'b', 1.0, 2.0])
arr4


array(['1', '2', 'a', 'b', '1.0', '2.0'], dtype='<U21')

### Numpy 다차원 배열

In [391]:
data5 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

arr5 = np.array(data5)
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### array 속성 확인

##### 데이터 타입 - dtype

In [392]:
arr1.dtype

dtype('int64')

In [393]:
arr2.dtype

dtype('float64')

In [394]:
arr3.dtype

dtype('float64')

In [395]:
arr4.dtype

dtype('<U21')

In [396]:
arr5.dtype

dtype('int64')

#### 배열의 형태 알기 - shape

In [397]:
# 1차원 배열 = 벡터
arr2.shape

(5,)

In [398]:
# 2차원 배열 = Matrix
arr5.shape

(3, 3)

## 범위를 지정해 배열 생성 - arange

In [399]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [400]:
arr2 = np.arange(5, 11)
arr2

array([ 5,  6,  7,  8,  9, 10])

In [401]:
arr3 = np.arange(5, 11, 2)
arr3

array([5, 7, 9])

In [402]:
arr4 = np.arange(5, 11, 2.0)
arr4

array([5., 7., 9.])

## linear한 배열 생성 - linspace

In [411]:
arr1 = np.linspace(1, 200, 27)
arr1

array([  1.        ,   8.65384615,  16.30769231,  23.96153846,
        31.61538462,  39.26923077,  46.92307692,  54.57692308,
        62.23076923,  69.88461538,  77.53846154,  85.19230769,
        92.84615385, 100.5       , 108.15384615, 115.80769231,
       123.46153846, 131.11538462, 138.76923077, 146.42307692,
       154.07692308, 161.73076923, 169.38461538, 177.03846154,
       184.69230769, 192.34615385, 200.        ])

In [412]:
len(arr1)

27

In [413]:
arr2 = np.linspace(5, 200)
arr2
len(arr2)

50

In [414]:
arr1 = np.linspace(1, 200, 27)
arr1

array([  1.        ,   8.65384615,  16.30769231,  23.96153846,
        31.61538462,  39.26923077,  46.92307692,  54.57692308,
        62.23076923,  69.88461538,  77.53846154,  85.19230769,
        92.84615385, 100.5       , 108.15384615, 115.80769231,
       123.46153846, 131.11538462, 138.76923077, 146.42307692,
       154.07692308, 161.73076923, 169.38461538, 177.03846154,
       184.69230769, 192.34615385, 200.        ])

In [415]:
len(arr1)

27

In [416]:
arr2 = np.linspace(5, 200)
arr2

array([  5.        ,   8.97959184,  12.95918367,  16.93877551,
        20.91836735,  24.89795918,  28.87755102,  32.85714286,
        36.83673469,  40.81632653,  44.79591837,  48.7755102 ,
        52.75510204,  56.73469388,  60.71428571,  64.69387755,
        68.67346939,  72.65306122,  76.63265306,  80.6122449 ,
        84.59183673,  88.57142857,  92.55102041,  96.53061224,
       100.51020408, 104.48979592, 108.46938776, 112.44897959,
       116.42857143, 120.40816327, 124.3877551 , 128.36734694,
       132.34693878, 136.32653061, 140.30612245, 144.28571429,
       148.26530612, 152.24489796, 156.2244898 , 160.20408163,
       164.18367347, 168.16326531, 172.14285714, 176.12244898,
       180.10204082, 184.08163265, 188.06122449, 192.04081633,
       196.02040816, 200.        ])

In [417]:
len(arr2)

50

In [418]:
# np.pi = 3.14159265....
arr3 = np.linspace(0, np.pi, 20)
arr3

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [419]:
len(arr3)

20

## 배열의 형태 변경 - reshape & shape = ..

In [420]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [421]:
# reshape-> 새로운 배열을 만든다.
arr2 = arr1.reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [422]:
arr3 = arr2.reshape(-1)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [423]:
arr4 = np.arange(16).reshape(4,4)
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [424]:
# arr4 자체의 shape을 변경
arr4.shape = (2,8)
arr4

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [425]:
# 3차원 행렬
arr5 = np.arange(27).reshape(3,3,3)
arr5

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

## 배열의 데이터 타입  -astype

In [427]:
# 소수 형태의 문자열
data1 = ['1.5', '.62', '3.14', '3.141592']
str_arr = np.array(data1)
str_arr

array(['1.5', '.62', '3.14', '3.141592'], dtype='<U8')

##### float형

In [428]:
float_arr = str_arr.astype(float) # or   float_arr = str_arr.astype('f')
float_arr

array([1.5     , 0.62    , 3.14    , 3.141592])

In [429]:
float_arr.dtype

dtype('float64')

##### int형

In [430]:
int_arr = float_arr.astype(int)
int_arr

array([1, 0, 3, 3])

In [431]:
int_arr.dtype

dtype('int64')

##### unicode형

In [432]:
# unicode = string
unicode_arr = int_arr.astype(str)
unicode_arr

array(['1', '0', '3', '3'], dtype='<U21')

In [433]:
unicode_arr.dtype

dtype('<U21')

##### 복소수형(complex)

In [439]:
# j=i
complex_arr = float_arr.astype(complex)
complex_arr

array([1.5     +0.j, 0.62    +0.j, 3.14    +0.j, 3.141592+0.j])

In [435]:
complex_arr.dtype

dtype('complex128')

In [438]:
complex_arr[0] = 2-2j # 복소수 추가. 

In [437]:
complex_arr

array([2.      -2.j, 0.62    +0.j, 3.14    +0.j, 3.141592+0.j])

## 난수 배열의 생성

### rand함수

In [441]:
rand_float = np.random.rand()
rand_float

0.47901008266283696

In [442]:
#size 지정
rand_float_arr1 = np.random.rand(4)
rand_float_arr1

array([0.68950182, 0.96954724, 0.92872655, 0.82179063])

In [443]:
rand_float_arr1.shape

(4,)

##### rand함수 다차원

In [444]:
rand_float_arr2 = np.random.rand(3,3)
rand_float_arr2

array([[0.28892615, 0.74186879, 0.09958419],
       [0.03407861, 0.047089  , 0.68796677],
       [0.16541832, 0.61922897, 0.85667402]])

In [445]:
rand_float_arr2.shape

(3, 3)

In [446]:
rand_float_arr3 = np.random.rand(3,3,5)
rand_float_arr3

array([[[0.3879362 , 0.21364063, 0.94168648, 0.15896388, 0.6993835 ],
        [0.58675968, 0.06995837, 0.56106689, 0.0026934 , 0.63627727],
        [0.42423574, 0.52380188, 0.81558216, 0.07622244, 0.78011161]],

       [[0.17820818, 0.57268899, 0.44891949, 0.52530148, 0.94866425],
        [0.88477476, 0.25352275, 0.00169204, 0.75889612, 0.44885208],
        [0.23524097, 0.84602856, 0.13729121, 0.83858887, 0.77702614]],

       [[0.855604  , 0.69354842, 0.46802271, 0.33687526, 0.9961289 ],
        [0.6272157 , 0.53677793, 0.70713457, 0.7480738 , 0.42921404],
        [0.52248062, 0.28962925, 0.93109079, 0.44816866, 0.99412571]]])

In [447]:
rand_float_arr3.shape

(3, 3, 5)

### 정수 난수를 생성하는 - randint

In [451]:
# 0~100
rand_int = np.random.randint(100)
rand_int

35

In [452]:
# 0~100 까지 size만큼
rand_int_arr1 = np.random.randint(100, size=(3,4))
rand_int_arr1

array([[68, 12,  9, 32],
       [23, 44, 43, 70],
       [29, 84, 54, 70]])

In [453]:
rand_int_arr1.shape

(3, 4)

In [454]:
rand_int_arr2 = np.random.randint(80, 100, size=(3,3,3))
rand_int_arr2

array([[[93, 94, 85],
        [88, 97, 92],
        [94, 97, 86]],

       [[88, 96, 97],
        [83, 80, 86],
        [95, 92, 82]],

       [[80, 98, 96],
        [88, 99, 87],
        [97, 80, 82]]])

In [455]:
rand_int_arr2.shape

(3, 3, 3)

### 정규분포 샘플링 np.random.randn

$${\mathrm  {N}}(0,1)$$

In [456]:
# 5,10의 표준 정규분포에서 샘플링
# 평균이 0 표준편차가 1
rand_n_arr = np.random.randn(5,10)
rand_n_arr

array([[ 0.51836826, -0.3841656 ,  0.94021237,  0.26738164,  0.01359325,
        -0.12936421, -0.16200017,  0.26950165,  0.69337011, -1.11180662],
       [-1.26153281,  0.30021908,  1.23943707,  0.13913128, -0.45452689,
         0.01783545, -1.84397623,  0.01274647,  0.08552545,  0.68253574],
       [ 1.2998308 ,  1.00897082, -0.18500086, -1.33305159, -0.26020863,
         0.08692719,  0.59991031, -1.54549323, -0.41890387, -1.09250493],
       [ 0.17708904, -0.16038047,  0.16239784,  1.21754689,  0.35238963,
        -0.61711122, -0.30237798,  1.45185331,  0.85320547,  0.71871504],
       [-0.10607157,  0.46686583,  0.52932801,  0.54938929,  0.12211169,
         0.95736119,  0.3046021 , -1.21151396, -0.08418879,  0.75532167]])

# 배열의 인덱싱과 슬라이싱

In [460]:
arr1 = np.arange(0, 60, 10)
arr1

array([ 0, 10, 20, 30, 40, 50])

In [461]:
# 리스트와 같음
print(arr1[0])
print(arr1[1])
print(arr1[-1])

0
10
50


In [462]:
arr1[:4]

array([ 0, 10, 20, 30])

In [463]:
arr1[3:]

array([30, 40, 50])

In [464]:
arr1[::2]

array([ 0, 20, 40])

##### 배열 수정하기

In [466]:

arr1[1] = 100
arr1

array([  0, 100,  20,  30,  40,  50])

##### 배열 부분 인덱싱

In [468]:

arr1[[1,4]]

array([100,  40])

### 2차원 배열 인덱싱 슬라이싱

In [474]:
# 2차원 배열 만들기
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [475]:
# row 가져오기
arr1[1]

array([3, 4, 5])

In [476]:
# row 가져온 후 column 지정
arr1[1][1]

4

In [477]:
# 값 변경하기
arr1[1][1] = 30
arr1

array([[ 0,  1,  2],
       [ 3, 30,  5],
       [ 6,  7,  8]])

In [479]:
# [row, column]
arr1[0,2] 

2

In [480]:
# 값 변경하기
arr1[0,2] = 10
arr1

array([[ 0,  1, 10],
       [ 3, 30,  5],
       [ 6,  7,  8]])

In [481]:
# row단위로 변경
arr1[2] = [3,3,3] 
arr1

array([[ 0,  1, 10],
       [ 3, 30,  5],
       [ 3,  3,  3]])

In [482]:
arr1[1:,1:] 

array([[30,  5],
       [ 3,  3]])

In [483]:
# slicing 대입
arr1[1:,1:] = np.array([[1,2],[3,4]])
arr1

array([[ 0,  1, 10],
       [ 3,  1,  2],
       [ 3,  3,  4]])

### 조건으로 인덱싱 슬라이싱

In [485]:
arr1 = np.arange(10, 100, 10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [486]:
arr1[arr1>50]

array([60, 70, 80, 90])

In [494]:
arr2 = np.arange(10, 170, 10).reshape(4, 4)
arr2

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [506]:
arr2[arr2%4 == 0]

array([ 20,  40,  60,  80, 100, 120, 140, 160])

In [507]:
arr2[:-1:2, ::2]

array([[ 10,  30],
       [ 90, 110]])

## NaN (not a number) & Inf(Infinity)

In [508]:
import numpy as np

In [509]:
np.nan

arr1 = np.array([1,2,3, np.nan, np.inf])
arr1

array([ 1.,  2.,  3., nan, inf])

## 특별한 형태의 배열 생성

In [510]:
# 모두 0인 배열
arr_zero_n = np.zeros(9)
arr_zero_n

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [511]:
# 모두 0인 3,3 배열
arr_zero_mxn = np.zeros((3,3))
arr_zero_mxn

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [512]:
# 모두 1인 배열
arr_one_n = np.ones(9)
arr_one_n

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [513]:
# 모두 1인 3,3 배열
arr_one_mxn = np.ones((3,3))
arr_one_mxn

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [514]:
# 단위 행렬 
arr_I = np.eye(5)
arr_I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [515]:
# 단위 행렬 다른 방법
arr_I2 = np.identity(5)
arr_I2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 배열의 연산

### shape이 같아야함

In [517]:
arr1 = np.arange(1.0,7)
arr2 = np.arange(10.0,70,10)

# repr은 클래스에서 __repr__을 호출하는 함수
print('arr1: %s \t shape:%s' % (repr(arr1), arr1.shape))
print('arr2: %s \t shape:%s' % (repr(arr2), arr2.shape))

arr1: array([1., 2., 3., 4., 5., 6.]) 	 shape:(6,)
arr2: array([10., 20., 30., 40., 50., 60.]) 	 shape:(6,)


### 배열의 덧셈

In [519]:
arr1 + 100

array([101., 102., 103., 104., 105., 106.])

In [520]:
arr1 + arr2

array([11., 22., 33., 44., 55., 66.])

### 배열의 뺄셈

In [521]:
arr1 - 5

array([-4., -3., -2., -1.,  0.,  1.])

In [522]:
arr1 - arr2

array([ -9., -18., -27., -36., -45., -54.])

### 배열의 곱셈

In [523]:
arr1 * 5

array([ 5., 10., 15., 20., 25., 30.])

In [524]:
arr1 * arr2

array([ 10.,  40.,  90., 160., 250., 360.])

### 배열의 나눗셈

In [525]:
arr1 / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        ])

In [526]:
arr1 / arr2

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

### 배열의 거듭제곱

In [527]:
arr1 ** 2

array([ 1.,  4.,  9., 16., 25., 36.])

In [528]:
arr1 ** arr2

array([1.00000000e+00, 1.04857600e+06, 2.05891132e+14, 1.20892582e+24,
       8.88178420e+34, 4.88736780e+46])

### 배열의 복합연산

In [529]:
(arr1 + 100) / arr2

array([10.1       ,  5.1       ,  3.43333333,  2.6       ,  2.1       ,
        1.76666667])

### 배열의 비교연산

In [531]:
arr2 > 20 # (조건으로 인덱싱)

array([False, False,  True,  True,  True,  True])

## 다차원 배열에서의 연산

In [532]:
arr1 = np.arange(1,9).reshape(2,4) 

arr2 = np.arange(10,90,10).reshape(2,4)

print('arr1: %s \t\t shape:%s' % (repr(arr1), arr1.shape))
print('arr2: %s \t shape:%s' % (repr(arr2), arr2.shape))

arr1: array([[1, 2, 3, 4],
       [5, 6, 7, 8]]) 		 shape:(2, 4)
arr2: array([[10, 20, 30, 40],
       [50, 60, 70, 80]]) 	 shape:(2, 4)


In [534]:
# 요소간 곱셈
arr1*arr2 

array([[ 10,  40,  90, 160],
       [250, 360, 490, 640]])

## 통계를 위한 연산
### 유용한 연산

### sum - 합 / mean - 평균

In [535]:
arr1 = np.arange(1, 11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [537]:
arr1.sum(), arr1.mean()

(55, 5.5)

### std - 표준편차 / var - 분산

In [538]:
# std = sqrt(var)
arr1.std(), arr1.var()

(2.8722813232690143, 8.25)

### min - 최소값 / max - 최대값

In [539]:
arr1.min(), arr1.max()

(1, 10)

### cumsum - 누적합 / cumprod - 누적곱

In [540]:
arr1.cumsum(), arr1.cumprod()

(array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55]),
 array([      1,       2,       6,      24,     120,     720,    5040,
          40320,  362880, 3628800]))

## 행렬 연산

In [542]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(6, 0, -1).reshape(3, 2)

print("A: %s" % repr(A))
print("B: %s" % repr(B))

A: array([[1, 2, 3],
       [4, 5, 6]])
B: array([[6, 5],
       [4, 3],
       [2, 1]])


### 행렬곱

In [550]:
# 지양
A.dot(B)

array([[20, 14],
       [56, 41]])

In [552]:
# 지양
np.dot(B,A)

array([[26, 37, 48],
       [16, 23, 30],
       [ 6,  9, 12]])

In [546]:
np.matmul(A, B)

array([[20, 14],
       [56, 41]])

In [553]:
A@B

array([[20, 14],
       [56, 41]])

### 전치행렬

In [554]:
A.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [556]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [557]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [558]:
B.transpose()

array([[6, 4, 2],
       [5, 3, 1]])

In [559]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [560]:
np.transpose(B)

array([[6, 4, 2],
       [5, 3, 1]])

### 단위행렬

In [561]:
A = np.arange(1, 5).reshape(2, 2)
B = np.arange(4, 0, -1).reshape(2, 2)

print("A: %s" % repr(A))
print("B: %s" % repr(B))

A: array([[1, 2],
       [3, 4]])
B: array([[4, 3],
       [2, 1]])


In [562]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [566]:
A@I

array([[1., 2.],
       [3., 4.]])

In [567]:
B@I

array([[4., 3.],
       [2., 1.]])

### 역행렬

In [568]:
A

array([[1, 2],
       [3, 4]])

In [569]:
B

array([[4, 3],
       [2, 1]])

In [574]:
Ai = np.linalg.inv(A)
Ai

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [577]:
A@Ai

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [578]:
Bi = np.linalg.inv(B)
Bi

array([[-0.5,  1.5],
       [ 1. , -2. ]])

In [579]:
B@Bi

array([[1., 0.],
       [0., 1.]])

In [580]:
Bi@B

array([[1., 0.],
       [0., 1.]])

### 행렬식

In [583]:
np.linalg.det(A)

-2.0000000000000004

In [584]:
np.linalg.det(B)

-2.0

In [385]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa


----