# Numpy

In [2]:
import numpy as np

# 배열

## sequence 데이터로부터 배열 생성

#### range 배열 생성

In [3]:
data1 = range(10)
arr1 = np.array(data1)

arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### list 배열 생성
##### \*\*\* python 내장 List와 다르게 numpy 배열은  type을 통일시킴

In [4]:
data2 = [0.1, 5, 4, 12, 0.5]
arr2 = np.array(data2)

arr2 # 모두 실수로 변환


array([ 0.1,  5. ,  4. , 12. ,  0.5])

#### list 배열 생성 with random

In [5]:
import random

# random.uniform = a<=N<=b 사이에 균등분포 랜덤
data3 = [random.uniform(-1, 1) for i in range(10)] # List Comprehension
arr3 = np.array(data3)
arr3

array([-0.25781776,  0.42955057, -0.04976543,  0.0695305 , -0.5342087 ,
       -0.63481099,  0.93476634, -0.45932195,  0.3168986 ,  0.52409895])

#### 속성혼합

In [6]:
# 혼합시 포함관계로
arr4 = np.array([1, 2, 'a', 'b', 1.0, 2.0])
arr4


array(['1', '2', 'a', 'b', '1.0', '2.0'], dtype='<U11')

### Numpy 다차원 배열

In [8]:
data5 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

arr5 = np.array(data5)
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### array 속성 확인

##### 데이터 타입 - dtype

In [9]:
arr1.dtype

dtype('int32')

In [10]:
arr2.dtype

dtype('float64')

In [11]:
arr3.dtype

dtype('float64')

In [12]:
arr4.dtype

dtype('<U11')

In [13]:
arr5.dtype

dtype('int32')

#### 배열의 형태 알기 - shape

In [14]:
# 1차원 배열 = 벡터
arr2.shape

(5,)

In [15]:
# 2차원 배열 = Matrix
arr5.shape

(3, 3)

## 범위를 지정해 배열 생성 - arange

In [16]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr2 = np.arange(5, 11)
arr2

array([ 5,  6,  7,  8,  9, 10])

In [18]:
arr3 = np.arange(5, 11, 2)
arr3

array([5, 7, 9])

In [19]:
arr4 = np.arange(5, 11, 2.0)
arr4

array([5., 7., 9.])

## linear한 배열 생성 - linspace

In [20]:
arr1 = np.linspace(1, 200, 27)
arr1

array([  1.        ,   8.65384615,  16.30769231,  23.96153846,
        31.61538462,  39.26923077,  46.92307692,  54.57692308,
        62.23076923,  69.88461538,  77.53846154,  85.19230769,
        92.84615385, 100.5       , 108.15384615, 115.80769231,
       123.46153846, 131.11538462, 138.76923077, 146.42307692,
       154.07692308, 161.73076923, 169.38461538, 177.03846154,
       184.69230769, 192.34615385, 200.        ])

In [21]:
len(arr1)

27

In [23]:
arr2 = np.linspace(5, 200)
arr2


array([  5.        ,   8.97959184,  12.95918367,  16.93877551,
        20.91836735,  24.89795918,  28.87755102,  32.85714286,
        36.83673469,  40.81632653,  44.79591837,  48.7755102 ,
        52.75510204,  56.73469388,  60.71428571,  64.69387755,
        68.67346939,  72.65306122,  76.63265306,  80.6122449 ,
        84.59183673,  88.57142857,  92.55102041,  96.53061224,
       100.51020408, 104.48979592, 108.46938776, 112.44897959,
       116.42857143, 120.40816327, 124.3877551 , 128.36734694,
       132.34693878, 136.32653061, 140.30612245, 144.28571429,
       148.26530612, 152.24489796, 156.2244898 , 160.20408163,
       164.18367347, 168.16326531, 172.14285714, 176.12244898,
       180.10204082, 184.08163265, 188.06122449, 192.04081633,
       196.02040816, 200.        ])

In [24]:
len(arr2)

50

In [25]:
# np.pi = 3.14159265....
arr3 = np.linspace(0, np.pi, 20)
arr3

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [26]:
len(arr3)

20

## 배열의 형태 변경 - reshape & shape = ..

In [27]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# reshape-> 새로운 배열을 만든다.
arr2 = arr1.reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
arr3 = arr2.reshape(-1)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
arr4 = np.arange(16).reshape(4,4)
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
# arr4 자체의 shape을 변경
arr4.shape = (2,8)
arr4

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [36]:
# 3차원 행렬
arr5 = np.arange(27).reshape(3,3,3)
arr5

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

## 배열의 데이터 타입  - astype

In [37]:
# 소수 형태의 문자열
data1 = ['1.5', '.62', '3.14', '3.141592']
str_arr = np.array(data1)
str_arr

array(['1.5', '.62', '3.14', '3.141592'], dtype='<U8')

In [38]:
str_arr.dtype

dtype('<U8')

##### float형

In [39]:
float_arr = str_arr.astype(float) # or   float_arr = str_arr.astype('f')
float_arr

array([1.5     , 0.62    , 3.14    , 3.141592])

In [40]:
float_arr.dtype

dtype('float64')

##### int형

In [41]:
int_arr = float_arr.astype(int)
int_arr

array([1, 0, 3, 3])

In [42]:
int_arr.dtype

dtype('int32')

##### unicode형

In [43]:
# unicode = string
unicode_arr = int_arr.astype(str)
unicode_arr

array(['1', '0', '3', '3'], dtype='<U11')

In [44]:
unicode_arr.dtype

dtype('<U11')

##### 복소수형(complex)

In [46]:
# j=i
complex_arr = float_arr.astype(complex)
complex_arr

array([1.5     +0.j, 0.62    +0.j, 3.14    +0.j, 3.141592+0.j])

In [47]:
complex_arr.dtype

dtype('complex128')

In [48]:
complex_arr[0] = 2-2j # 복소수 추가. 

In [49]:
complex_arr

array([2.      -2.j, 0.62    +0.j, 3.14    +0.j, 3.141592+0.j])

## 난수 배열의 생성

### rand함수

In [53]:
# np.random.~~
rand_float = np.random.rand()
rand_float

0.6910200488235301

In [54]:
# size 지정
rand_float_arr1 = np.random.rand(4)
rand_float_arr1

array([0.74199854, 0.16255891, 0.4703956 , 0.54500712])

In [55]:
rand_float_arr1.shape

(4,)

##### rand함수 다차원

In [56]:
rand_float_arr2 = np.random.rand(3,3)
rand_float_arr2

array([[0.76791481, 0.43812652, 0.07056864],
       [0.81116049, 0.42355379, 0.74106309],
       [0.38219395, 0.53251952, 0.56140428]])

In [57]:
rand_float_arr2.shape

(3, 3)

In [61]:
rand_float_arr3 = np.random.rand(3,3,3)
rand_float_arr3

array([[[0.23519715, 0.45603081, 0.71539444],
        [0.37786694, 0.80489011, 0.3664591 ],
        [0.20293404, 0.56395459, 0.082438  ]],

       [[0.60426201, 0.12591627, 0.32035709],
        [0.8973234 , 0.72306296, 0.25770123],
        [0.01339286, 0.5581449 , 0.25067512]],

       [[0.05049094, 0.98686725, 0.37723082],
        [0.48103027, 0.79255255, 0.89016909],
        [0.99486718, 0.27897016, 0.5319561 ]]])

In [62]:
rand_float_arr3.shape

(3, 3, 3)

### 정수 난수를 생성하는 - randint

In [66]:
# 0~100
rand_int = np.random.randint(100)
rand_int

51

In [67]:
# 0~100 까지 size만큼
rand_int_arr1 = np.random.randint(100, size=(3,4))
rand_int_arr1

array([[39, 74,  0, 23],
       [36, 93,  9, 81],
       [12, 68, 12, 79]])

In [68]:
rand_int_arr1.shape

(3, 4)

In [69]:
# 80~ 100 정수중에서 3,3,3 형태의 배열을 난수로 생성한다.
rand_int_arr2 = np.random.randint(80, 100, size=(3,3,3))
rand_int_arr2

array([[[88, 82, 80],
        [85, 92, 93],
        [98, 84, 84]],

       [[90, 93, 83],
        [84, 96, 95],
        [97, 98, 84]],

       [[86, 94, 81],
        [80, 90, 99],
        [89, 83, 97]]])

In [70]:
rand_int_arr2.shape

(3, 3, 3)

### 정규분포 샘플링 np.random.randn

$${\mathrm  {N}}(0,1)$$

In [71]:
# 5,10의 표준 정규분포에서 샘플링
# 평균이 0 표준편차가 1
rand_n_arr = np.random.randn(5,10)
rand_n_arr

array([[ 2.64539624e+00, -3.92990170e-01, -3.53234599e-01,
         4.19785386e-01,  7.43322951e-01, -9.48817106e-02,
        -1.10923720e+00,  4.32414385e-01, -4.08547712e-01,
        -9.58036144e-02],
       [-1.05138674e+00,  1.49753180e+00,  2.11580668e-01,
        -1.75549259e-01,  3.46790417e-01,  2.09892439e+00,
         1.01496280e+00, -1.40636995e+00,  4.37985750e-01,
         9.43620934e-01],
       [-1.59747210e+00,  2.07985188e+00,  5.24285459e-02,
        -1.17238885e+00,  9.85081284e-01,  1.06951304e+00,
        -2.59959142e-01, -4.32053378e-01,  1.34879910e+00,
         1.08147663e-01],
       [-1.05717063e+00,  9.30249409e-01,  7.99212706e-02,
        -2.38679017e-03, -1.25798852e+00, -2.01298650e+00,
         1.97919486e-01, -1.42333855e+00,  1.05368881e+00,
         1.00317648e+00],
       [ 4.85021703e-01,  1.95662910e-02, -6.24924182e-01,
         6.30466204e-01, -5.13504210e-01,  9.23255213e-01,
        -1.55983523e+00, -6.72736068e-01,  1.19983134e+00,
        -3.

# 배열의 인덱싱과 슬라이싱

In [72]:
arr1 = np.arange(0, 60, 10)
arr1

array([ 0, 10, 20, 30, 40, 50])

In [73]:
# 리스트와 같음
print(arr1[0])
print(arr1[1])
print(arr1[-1])

0
10
50


In [74]:
arr1[:4]

array([ 0, 10, 20, 30])

In [75]:
arr1[3:]

array([30, 40, 50])

In [76]:
arr1[::2]

array([ 0, 20, 40])

##### 배열 수정하기

In [77]:
arr1[1] = 100
arr1

array([  0, 100,  20,  30,  40,  50])

##### 배열 부분 인덱싱

In [79]:
arr1[[1,4, 3]]

array([100,  40,  30])

### 2차원 배열 인덱싱 슬라이싱

In [81]:
# 2차원 배열 만들기
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
# row 가져오기
arr1[1]

array([3, 4, 5])

In [83]:
# row 가져온 후 column 지정
arr1[1][1]

4

In [84]:
# 값 변경하기
arr1[1][1] = 30
arr1

array([[ 0,  1,  2],
       [ 3, 30,  5],
       [ 6,  7,  8]])

In [85]:
# [row, column]
arr1[0, 2] 

2

In [86]:
# 값 변경하기
arr1[0, 2] = 10
arr1

array([[ 0,  1, 10],
       [ 3, 30,  5],
       [ 6,  7,  8]])

In [87]:
# row단위로 변경
arr1[2] = [3,3,3] 
arr1

array([[ 0,  1, 10],
       [ 3, 30,  5],
       [ 3,  3,  3]])

In [88]:
arr1[1:,1:] 

array([[30,  5],
       [ 3,  3]])

In [89]:
# slicing 대입
arr1[1:,1:] = np.array([[1,2],[3,4]])
arr1

array([[ 0,  1, 10],
       [ 3,  1,  2],
       [ 3,  3,  4]])

### 조건으로 인덱싱 슬라이싱

In [90]:
arr1 = np.arange(10, 100, 10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [91]:
arr1[arr1>50]

array([60, 70, 80, 90])

In [92]:
arr2 = np.arange(10, 170, 10).reshape(4, 4)
arr2

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [93]:
arr2[arr2%4 == 0]

array([ 20,  40,  60,  80, 100, 120, 140, 160])

In [94]:
arr2[:-1:2, ::2]

array([[ 10,  30],
       [ 90, 110]])

## NaN (not a number) & Inf(Infinity)

In [ ]:
import numpy as np

In [95]:
np.nan

arr1 = np.array([1,2,3, np.nan, np.inf])
arr1

array([ 1.,  2.,  3., nan, inf])

In [97]:
np.arange(9).reshape(3,3).dtype

dtype('int32')

In [96]:
arr1.dtype

dtype('float64')

## 리스트 인덱싱 & 2차원인덱싱

In [100]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [126]:
arr1[0, 0]

0

In [107]:
arr2 = np.arange(10, 20)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [108]:
arr2[[0, 7]]

array([10, 17, 13, 18])

## 특별한 형태의 배열 생성

In [127]:
# 모두 0인 배열
arr_zero_n = np.zeros(9)
arr_zero_n

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [128]:
# 모두 0인 3,3 배열
arr_zero_mxn = np.zeros((3,3))
arr_zero_mxn

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [129]:
# 모두 1인 배열
arr_one_n = np.ones(9)
arr_one_n

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [130]:
# 모두 1인 3,3 배열
arr_one_mxn = np.ones((3,3))
arr_one_mxn

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [136]:
# 단위 행렬 
arr_I = np.eye(4)
arr_I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [137]:
# 단위 행렬 다른 방법
arr_I2 = np.identity(5)
arr_I2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 배열의 연산

### shape이 같아야함

In [138]:
arr1 = np.arange(1.0,7)
arr2 = np.arange(10.0,70,10)

# repr은 클래스에서 __repr__을 호출하는 함수
print('arr1: %s \t shape:%s' % (repr(arr1), arr1.shape))
print('arr2: %s \t shape:%s' % (repr(arr2), arr2.shape))

arr1: array([1., 2., 3., 4., 5., 6.]) 	 shape:(6,)
arr2: array([10., 20., 30., 40., 50., 60.]) 	 shape:(6,)


### 배열의 덧셈

In [139]:
arr1 + 100

array([101., 102., 103., 104., 105., 106.])

In [140]:
arr1 + arr2

array([11., 22., 33., 44., 55., 66.])

### 배열의 뺄셈

In [141]:
arr1 - 5

array([-4., -3., -2., -1.,  0.,  1.])

In [142]:
arr1 - arr2

array([ -9., -18., -27., -36., -45., -54.])

### 배열의 곱셈

In [143]:
arr1 * 5

array([ 5., 10., 15., 20., 25., 30.])

In [144]:
arr1 * arr2

array([ 10.,  40.,  90., 160., 250., 360.])

### 배열의 나눗셈

In [145]:
arr1 / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        ])

In [146]:
arr1 / arr2

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

### 배열의 거듭제곱

In [147]:
arr1 ** 2

array([ 1.,  4.,  9., 16., 25., 36.])

In [148]:
arr1 ** arr2

array([1.00000000e+00, 1.04857600e+06, 2.05891132e+14, 1.20892582e+24,
       8.88178420e+34, 4.88736780e+46])

### 배열의 복합연산

In [149]:
(arr1 + 100) / arr2

array([10.1       ,  5.1       ,  3.43333333,  2.6       ,  2.1       ,
        1.76666667])

### 배열의 비교연산

In [200]:
arr2 = np.arange(10)

In [201]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [203]:
arr2 > 5 # (조건으로 인덱싱)

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [204]:
arr2[[False, False, False, False, False, False,  True,  True,  True, True]]

array([6, 7, 8, 9])

In [210]:
arr2 = np.arange(9).reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [212]:
arr2[[1, 2], [0, 1]]

array([3, 7])

## 다차원 배열에서의 연산

In [155]:
arr1 = np.arange(1,9).reshape(2,4) 

arr2 = np.arange(10,90,10).reshape(2,4)

print('arr1: %s \t\t shape:%s' % (repr(arr1), arr1.shape))
print('arr2: %s \t shape:%s' % (repr(arr2), arr2.shape))

arr1: array([[1, 2, 3, 4],
       [5, 6, 7, 8]]) 		 shape:(2, 4)
arr2: array([[10, 20, 30, 40],
       [50, 60, 70, 80]]) 	 shape:(2, 4)


In [156]:
# 요소간 곱셈
arr1*arr2 

array([[ 10,  40,  90, 160],
       [250, 360, 490, 640]])

## 통계를 위한 연산
### 유용한 연산

### sum - 합 / mean - 평균

In [157]:
arr1 = np.arange(1, 11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [158]:
arr1.sum(), arr1.mean()

(55, 5.5)

### std - 표준편차 / var - 분산

In [159]:
# std = sqrt(var)
arr1.std(), arr1.var()

(2.8722813232690143, 8.25)

### min - 최소값 / max - 최대값

In [160]:
arr1.min(), arr1.max()

(1, 10)

### cumsum - 누적합 / cumprod - 누적곱

In [162]:
arr1.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [163]:
arr1.cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

## 행렬 연산

In [164]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(6, 0, -1).reshape(3, 2)

print("A: %s" % repr(A))
print("B: %s" % repr(B))

A: array([[1, 2, 3],
       [4, 5, 6]])
B: array([[6, 5],
       [4, 3],
       [2, 1]])


### 행렬곱

In [165]:
# 지양
A.dot(B)

array([[20, 14],
       [56, 41]])

In [166]:
# 지양
np.dot(B,A)

array([[26, 37, 48],
       [16, 23, 30],
       [ 6,  9, 12]])

In [167]:
np.matmul(A, B)

array([[20, 14],
       [56, 41]])

In [168]:
A@B

array([[20, 14],
       [56, 41]])

In [169]:
B@A

array([[26, 37, 48],
       [16, 23, 30],
       [ 6,  9, 12]])

### 전치행렬

In [170]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [171]:
A.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [172]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [173]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [175]:
B

array([[6, 5],
       [4, 3],
       [2, 1]])

In [176]:
B.transpose()

array([[6, 4, 2],
       [5, 3, 1]])

In [177]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [178]:
np.transpose(B)

array([[6, 4, 2],
       [5, 3, 1]])

### 단위행렬

In [179]:
A = np.arange(1, 5).reshape(2, 2)
B = np.arange(4, 0, -1).reshape(2, 2)

print("A: %s" % repr(A))
print("B: %s" % repr(B))

A: array([[1, 2],
       [3, 4]])
B: array([[4, 3],
       [2, 1]])


In [180]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [181]:
A@I

array([[1., 2.],
       [3., 4.]])

In [182]:
B@I

array([[4., 3.],
       [2., 1.]])

### 역행렬

In [183]:
A

array([[1, 2],
       [3, 4]])

In [184]:
B

array([[4, 3],
       [2, 1]])

In [185]:
Ai = np.linalg.inv(A)
Ai

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [186]:
A@Ai

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [187]:
Bi = np.linalg.inv(B)
Bi

array([[-0.5,  1.5],
       [ 1. , -2. ]])

In [188]:
B@Bi

array([[1., 0.],
       [0., 1.]])

In [189]:
Bi@B

array([[1., 0.],
       [0., 1.]])

### 행렬식

In [190]:
np.linalg.det(A)

-2.0000000000000004

In [191]:
np.linalg.det(B)

-2.0

In [192]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '


----