In [1]:
import numpy as np

In [2]:
a = np.array(range(10))

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(a)

numpy.ndarray

In [5]:
l1 = [5,4,8,10]
b = np.array(l1)
b

array([ 5,  4,  8, 10])

In [6]:
a.dtype

dtype('int32')

In [7]:
b.dtype

dtype('int32')

In [9]:
l2 = [1, 2.0, 3, 'a']
l2

[1, 2.0, 3, 'a']

In [10]:
np.array(l2)

array(['1', '2.0', '3', 'a'], dtype='<U32')

In [13]:
l3 = [1, 2.0, 3.0 ,5.9]
c = np.array(l3)
c

array([1. , 2. , 3. , 5.9])

In [14]:
c.dtype

dtype('float64')

In [15]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
b

array([ 5,  4,  8, 10])

In [17]:
c

array([1. , 2. , 3. , 5.9])

In [18]:
a.shape

(10,)

In [19]:
b.shape

(4,)

In [20]:
c.shape

(4,)

# 차원의 개념 

In [21]:
l1 = [[1,2], [3, 4]]
a = np.array(l1)
a

array([[1, 2],
       [3, 4]])

In [22]:
a.dtype

dtype('int32')

In [23]:
a.shape

(2, 2)

In [24]:
l2 = [[1,2,3], [3, 4]]
b = np.array(l2)
b

array([list([1, 2, 3]), list([3, 4])], dtype=object)

(2,)

In [29]:
range(10)

range(0, 10)

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [34]:
np.linspace(10, 20, 9)

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])

In [35]:
np.linspace(10, 20, 10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [36]:
np.linspace(10, 20)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

## Shape 

In [41]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [42]:
a.shape

(8,)

In [43]:
b = a.reshape(2, 4)

In [44]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [45]:
b.shape

(2, 4)

### 또 다른 방법 

In [59]:
a.shape = (2,4)

In [60]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [57]:
a.shape = (8,)

In [58]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [61]:
a.shape = -1

In [62]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

### astype

In [64]:
a = np.linspace(0, 100)

In [65]:
a.dtype

dtype('float64')

In [69]:
b = a.astype(str)
b

array(['0.0', '2.0408163265306123', '4.081632653061225',
       '6.122448979591837', '8.16326530612245', '10.204081632653061',
       '12.244897959183675', '14.285714285714286', '16.3265306122449',
       '18.367346938775512', '20.408163265306122', '22.448979591836736',
       '24.48979591836735', '26.53061224489796', '28.571428571428573',
       '30.612244897959183', '32.6530612244898', '34.69387755102041',
       '36.734693877551024', '38.775510204081634', '40.816326530612244',
       '42.85714285714286', '44.89795918367347', '46.93877551020408',
       '48.9795918367347', '51.02040816326531', '53.06122448979592',
       '55.10204081632653', '57.142857142857146', '59.183673469387756',
       '61.224489795918366', '63.26530612244898', '65.3061224489796',
       '67.34693877551021', '69.38775510204081', '71.42857142857143',
       '73.46938775510205', '75.51020408163265', '77.55102040816327',
       '79.59183673469389', '81.63265306122449', '83.6734693877551',
       '85.71428571428572

In [71]:
c = a.astype(int)
c

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [75]:
np.random.rand(2,3)

array([[0.31725586, 0.62049341, 0.58846836],
       [0.97931254, 0.00446961, 0.16888171]])

In [78]:
np.random.randint(1, 10, 28).reshape(7,4)

array([[6, 2, 7, 6],
       [7, 8, 7, 1],
       [7, 3, 6, 8],
       [4, 1, 5, 5],
       [1, 4, 2, 2],
       [7, 4, 7, 5],
       [7, 2, 8, 2]])

In [79]:
np.random.randn(2,2)

array([[ 0.67625979, -0.14964622],
       [-0.37747258, -0.47106879]])

# 인덱스 

In [83]:
a = np.linspace(1, 20, 9)
a

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [89]:
a[8]

20.0

In [90]:
a = a.reshape(3,3)
a

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [91]:
a[1][2]

12.875

In [92]:
a[1, 2]

12.875

In [93]:
a[1, 2]

12.875

In [96]:
a[:]

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [97]:
a[1:]

array([[ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [98]:
a[:2]

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875]])

In [99]:
a[2,2]

20.0

In [102]:
a[:, 1:]

array([[ 3.375,  5.75 ],
       [10.5  , 12.875],
       [17.625, 20.   ]])

In [103]:
a[:, :2]

array([[ 1.   ,  3.375],
       [ 8.125, 10.5  ],
       [15.25 , 17.625]])

In [105]:
b = a.reshape(-1)

In [106]:
b

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [107]:
b[1::2]

array([ 3.375,  8.125, 12.875, 17.625])

In [110]:
a

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [112]:
a[::2, ::2]

array([[ 1.  ,  5.75],
       [15.25, 20.  ]])

In [116]:
b

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [117]:
b[b>10]

array([10.5  , 12.875, 15.25 , 17.625, 20.   ])

In [118]:
a

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [127]:
a[1, a[1]>9]

array([10.5  , 12.875])

In [130]:
np.nan

nan

In [131]:
np.inf

inf

### 연산

In [133]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
a + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [136]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
b = np.arange(1, 11)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [139]:
a + b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [140]:
a -b

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [141]:
a*b

array([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

In [142]:
a/b

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])