In [1]:
import torch
# 과거엔 Variable 현재는 tensor자체에 지원
# from torch.autograd import Variable

# Autograd 

In [2]:
x = torch.ones(1)
print(x)
x.requires_grad

tensor([1.])


False

In [3]:
y = torch.ones(1)
y.requires_grad

False

In [4]:
z = x + y
z

tensor([2.])

In [5]:
z.requires_grad

False

In [6]:
# requires_grad_() 호출시 
# 계산 결과도 rquires_grad 있음
x.requires_grad_()
x.requires_grad

True

In [8]:
z = x + y

In [9]:
z.requires_grad

True

### 2차원

In [38]:
x = torch.rand(2,2)
y = torch.rand(2,2)
# x = Variable(tensor, requires_grad=True)

x.requires_grad_()
print(x)
print(y)

tensor([[0.7527, 0.4802],
        [0.2440, 0.7132]], requires_grad=True)
tensor([[0.3591, 0.2425],
        [0.3028, 0.4549]])


In [22]:
# 계산 될때마다 자동으로 Backward 적용
print(x.sum())
print(x.sqrt())
print(x**2)
print(x)

tensor(2.2004, grad_fn=<SumBackward0>)
tensor([[0.9842, 0.6075],
        [0.7660, 0.5252]], grad_fn=<SqrtBackward>)
tensor([[0.9383, 0.1362],
        [0.3444, 0.0761]], grad_fn=<PowBackward0>)
tensor([[0.9686, 0.3690],
        [0.5868, 0.2759]], requires_grad=True)


In [23]:
x.sum(), x.sqrt(), x**2, x

(tensor(2.2004, grad_fn=<SumBackward0>), tensor([[0.9842, 0.6075],
         [0.7660, 0.5252]], grad_fn=<SqrtBackward>), tensor([[0.9383, 0.1362],
         [0.3444, 0.0761]], grad_fn=<PowBackward0>), tensor([[0.9686, 0.3690],
         [0.5868, 0.2759]], requires_grad=True))

In [24]:
print(y.sum())
print(y.sqrt())
print(y**2)
print(y)

tensor(1.4528)
tensor([[0.3678, 0.5344],
        [0.7509, 0.6842]])
tensor([[0.0183, 0.0816],
        [0.3179, 0.2191]])
tensor([[0.1353, 0.2856],
        [0.5638, 0.4681]])


# Backward

In [39]:
y = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32, requires_grad=True)
y

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [26]:
y.sum()

tensor(10., grad_fn=<SumBackward0>)

In [27]:
z = y.max()
z

tensor(4., grad_fn=<MaxBackward1>)

In [40]:
z = 2*y + 1
z

tensor([[3., 5.],
        [7., 9.]], grad_fn=<AddBackward0>)

In [41]:
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)

print("")

print("y.grad :", y.grad) # 아직X
print("z.grad :", z.grad) # 아직X

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)

y.requires_grad : True
z.requires_grad : True

y.grad : None
z.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward0 object at 0x000000000871AB70>


In [42]:
z.backward(torch.eye(2,2, dtype=torch.float32))
# z.backward(torch.eye(2,2, dtype=torch.float32))

In [43]:
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)

print("")

print("y.grad :", y.grad) # 역전파 (z.backward 후)
print("z.grad :", z.grad) # 아직X

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)

y.requires_grad : True
z.requires_grad : True

y.grad : tensor([[2., 0.],
        [0., 2.]])
z.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward0 object at 0x0000000008715390>


In [54]:
z = 2* y

In [55]:
out = z * 2 * z ** 2
out

tensor([[  16.,  128.],
        [ 432., 1024.]], grad_fn=<MulBackward0>)

In [56]:
out.backward(torch.eye(2))

In [57]:
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)
print("out.requires_grad :", out.requires_grad)

print("")

print("y.grad :", y.grad)
print("z.grad :", z.grad)
print("out.grad :", out.grad)

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)
print("out.grad_fn :", out.grad_fn)

y.requires_grad : True
z.requires_grad : True
out.requires_grad : True

y.grad : tensor([[  98.,    0.],
        [   0., 1538.]])
z.grad : None
out.grad : None

y.grad_fn : None
z.grad_fn : <MulBackward0 object at 0x0000000008721160>
out.grad_fn : <MulBackward0 object at 0x0000000008721320>


In [36]:
out.backward(torch.eye(2))

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [46]:
out.grad_fn, out.grad_fn.next_functions

(<MulBackward0 at 0x871a6a0>,
 ((<MulBackward0 at 0x871a710>, 0), (<PowBackward0 at 0x871a860>, 0)))