In [2]:
import torch
# 과거엔 Variable 현재는 tensor자체에 지원
# from torch.autograd import Variable

# Autograd 

In [138]:
x = torch.ones(1)
x.requires_grad

False

In [139]:
y = torch.ones(1)
y.requires_grad

False

In [140]:
z = x + y

In [144]:
z.requires_grad

False

In [147]:
# requires_grad_() 호출시 
# 계산 결과도 rquires_grad 있음
x.requires_grad_()
x.requires_grad

True

In [148]:
z = x + y

In [149]:
z.requires_grad

True

### 2차원

In [150]:
x = torch.rand(2,2)
y = torch.rand(2,2)
# x = Variable(tensor, requires_grad=True)

x.requires_grad_()
print(x)
print(y)

tensor([[0.9010, 0.7502],
        [0.2399, 0.1490]], requires_grad=True)
tensor([[0.8947, 0.8298],
        [0.5737, 0.6848]])


In [151]:
# 계산 될때마다 자동으로 Backward 적용
print(x.sum())
print(x.sqrt())
print(x**2)
print(x)

tensor(2.0401, grad_fn=<SumBackward0>)
tensor([[0.9492, 0.8661],
        [0.4898, 0.3861]], grad_fn=<SqrtBackward>)
tensor([[0.8118, 0.5628],
        [0.0576, 0.0222]], grad_fn=<PowBackward0>)
tensor([[0.9010, 0.7502],
        [0.2399, 0.1490]], requires_grad=True)


In [152]:
x.sum(), x.sqrt(), x**2, x

(tensor(2.0401, grad_fn=<SumBackward0>), tensor([[0.9492, 0.8661],
         [0.4898, 0.3861]], grad_fn=<SqrtBackward>), tensor([[0.8118, 0.5628],
         [0.0576, 0.0222]], grad_fn=<PowBackward0>), tensor([[0.9010, 0.7502],
         [0.2399, 0.1490]], requires_grad=True))

In [153]:
print(y.sum())
print(y.sqrt())
print(y**2)
print(y)

tensor(2.9829)
tensor([[0.9459, 0.9109],
        [0.7574, 0.8275]])
tensor([[0.8005, 0.6885],
        [0.3291, 0.4689]])
tensor([[0.8947, 0.8298],
        [0.5737, 0.6848]])


# Backward

In [273]:
y = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32, requires_grad=True)
y

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [274]:
y.sum()

tensor(10., grad_fn=<SumBackward0>)

In [275]:
y.max()

tensor(4., grad_fn=<MaxBackward1>)

In [276]:
z = 2*y + 1
z

tensor([[3., 5.],
        [7., 9.]], grad_fn=<AddBackward0>)

In [277]:
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)

print("")

print("y.grad :", y.grad) # 아직X
print("z.grad :", z.grad) # 아직X

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)

y.requires_grad : True
z.requires_grad : True

y.grad : None
z.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward0 object at 0x11ac37780>


In [278]:
z.backward(torch.eye(2,2, dtype=torch.float32))

In [279]:
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)

print("")

print("y.grad :", y.grad) # 역전파 (z.backward 후)
print("z.grad :", z.grad) # 아직X

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)

y.requires_grad : True
z.requires_grad : True

y.grad : tensor([[2., 0.],
        [0., 2.]])
z.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward0 object at 0x11aa5d978>


In [308]:
out = z * 2 * z**2
out

tensor([[  54.,  250.],
        [ 686., 1458.]], grad_fn=<MulBackward0>)

In [309]:
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)
print("out.requires_grad :", out.requires_grad)

print("")

print("y.grad :", y.grad)
print("z.grad :", z.grad)
print("out.grad :", out.grad)

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)
print("out.grad_fn :", out.grad_fn)

y.requires_grad : True
z.requires_grad : True
out.requires_grad : True

y.grad : tensor([[2., 0.],
        [0., 2.]])
z.grad : None
out.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward0 object at 0x11ac670b8>
out.grad_fn : <MulBackward0 object at 0x11ac67438>


In [310]:
out.grad_fn, out.grad_fn.next_functions

(<MulBackward0 at 0x11ac652b0>,
 ((<MulBackward0 at 0x11ac65780>, 0), (<PowBackward0 at 0x11ac65630>, 0)))