In [1]:
import torch.cuda # GPU 지원
from torch import Storage # 1차원 배열, single data type 저장소
import torch.nn # NN 모듈s --> Parameter, Container, Layer, Utility
import torch.nn.functional # NN functions
import torch.nn.init # initialize 
import torch.optim # 최적화 알고리즘
import torch.autograd # Gradient 자동 계산


In [2]:
import torch.distributed # 분산처리
import torch.distributions # 분포

import torch.multiprocessing # 멀티프로세싱 모듈 wrapper

In [3]:
import torch.utils 
from torch.utils import bottleneck # Bottleneck 디버깅
from torch.utils import checkpoint 
from torch.utils import cpp_extension # cpp3지원
from torch.utils import data
from torch.utils import dlpack
from torch.utils import model_zoo

In [4]:
import torch.jit # Torch Script

In [5]:
import numpy as np

# 텐서 (Tensor) 기본
- [torch.Tensor](https://pytorch.org/docs/stable/tensors.html)

In [24]:
torch.Tensor(2,2)

tensor([[8.2957e-43, 0.0000e+00],
        [1.4013e-45, 0.0000e+00]])

In [9]:
x = torch.Tensor(2,2) # = torch.FloatTensor
x

tensor([[7.8473e-43, 0.0000e+00],
        [1.4013e-45, 0.0000e+00]])

In [10]:
print('type: ', x.type())
print('size: ', x.size())
print('개수: ', x.numel())


type:  torch.FloatTensor
size:  torch.Size([2, 2])
개수:  4


In [11]:
# 4차원
x2 = torch.Tensor(4,3,2,1)
x2

tensor([[[[1.2051e-43],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00]]],


        [[[0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00]]],


        [[[0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00]]],


        [[[0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00]]]])

In [12]:
print('type: ', x2.type())
print('size: ', x2.size())
print('개수: ', x2.numel())

type:  torch.FloatTensor
size:  torch.Size([4, 3, 2, 1])
개수:  24


# 텐서를 만드는 또 다른 방법

In [13]:
# 영행렬
a = torch.zeros(4, 4)
print('a:', a)

# 일행렬
b = torch.ones(4,4)
print('b:',b)

# 단위 행렬
c = torch.eye(4,4) 
print('c:',c)

# 0과1사이 난수
d = torch.rand(4,4)
print('d:',d)

# 정규분포 추출 N(0,1)
e = torch.randn(4,4)
print('e:',e)


a: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
b: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
c: tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
d: tensor([[0.5718, 0.9800, 0.6531, 0.7901],
        [0.4243, 0.6699, 0.5234, 0.4528],
        [0.9779, 0.2034, 0.1950, 0.6633],
        [0.0758, 0.1773, 0.6999, 0.1111]])
e: tensor([[-0.1951, -1.5715, -0.5372, -1.5828],
        [-0.9684, -1.1073, -0.0487, -1.2319],
        [-0.4602, -0.9341, -0.0081,  0.6155],
        [-0.5450,  0.4151, -0.0992, -0.2881]])


In [14]:
x3 = torch.arange(0, 3, step=0.3) # np.arange()
x3

tensor([0.0000, 0.3000, 0.6000, 0.9000, 1.2000, 1.5000, 1.8000, 2.1000, 2.4000,
        2.7000])

In [15]:
torch.Tensor([[6,2],[3,4],[5,6]])

tensor([[6., 2.],
        [3., 4.],
        [5., 6.]])

In [16]:
numpy_test = np.array([[5,6],[10,11]])
numpy_test

array([[ 5,  6],
       [10, 11]])

In [19]:
a = torch.from_numpy(numpy_test)
a

tensor([[ 5,  6],
        [10, 11]], dtype=torch.int32)

In [20]:
a.numpy()

array([[ 5,  6],
       [10, 11]])

# 인덱싱, 슬라이싱

In [ ]:
x4 = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
x4

In [ ]:
x4[0:2,:]

In [ ]:
x4[1]

In [ ]:
x4[0,:]

In [ ]:
# 값 변경
x4[0:1,:] = torch.Tensor([62,72,80])
x4

In [ ]:
# 값 변경
x4[1] = torch.Tensor([200,78, 89])
x4

In [ ]:
# https://pytorch.org/docs/stable/torch.html#torch.split
x5 = torch.split(x4, split_size_or_sections=1,dim=0) # split함.
x5


In [ ]:
a, b, c = x5

In [ ]:
# https://pytorch.org/docs/stable/torch.html#torch.split
x6 = torch.split(x4, split_size_or_sections=1,dim=1) # split함.
x6

In [ ]:
y1 = torch.cat((a,b,c), dim=1)
print(y1)
print('size: ', y1.size())

In [ ]:
y2 = torch.cat((a,b,c), dim=0)
print(y2)
print('size: ', y2.size())

In [ ]:
# 하나 더 쌓기
y3 = torch.stack(x5, dim=1)
print(y3)
print('size: ', y3.size())

In [ ]:
x7 = torch.randn(3,3)
print('x7:',x7)
print()

# mask함수
mask  = torch.ByteTensor([[1,0,0],[1,1,1],[0,1,0]])
print('mask:', mask)
print()

out = torch.masked_select(x7, mask)
print('masked_select:', out)
print()

# 차원 변경(Reshape) - View

In [ ]:
x8 = torch.zeros(2,2,1)
x8

In [ ]:
x8.view(2,2)

In [ ]:
x8.view(-1) # -1 = Automatic

In [ ]:
x8.view(-1,2)

In [ ]:
x7.view(4)

In [ ]:
x8 = x7.squeeze() # 1차원 빼기
print('X7:', x7)
print('x7 size:', x7.size())
print()
print('X8:', x8)
print('x8 size:', x8.size())

In [ ]:
# unsqueeze(<차원의 index>)
x8.unsqueeze(0)


# 연산

In [ ]:
x9 = torch.FloatTensor([[10,20,30],[40,50,60]])
x10 = torch.FloatTensor([[1,2,3],[4,5,6]])
print('x9: ', x9)
print('x10: ', x10)


In [ ]:
print(x9  + x10)
print(x9.add(x10))
print(torch.add(x9, x10))

In [ ]:
print(x9 - x10)
print(x9.sub(x10))
print(x10.sub(x9))
print(torch.sub(x10, x9))

In [ ]:
x10[1] + 12

In [ ]:

print(x9 * x10)
print(x9.mul(x10))
print(x10.mul(x9))
print(torch.mul(x10, x9))


In [ ]:
x10 * 10


# 연산2

In [ ]:
# 거듭제곱 - power
x9.pow(2), torch.pow(x9,2), x9 ** 2

In [ ]:
x9.sqrt()

In [ ]:
print(x10.log())
print(torch.log(x10))

In [ ]:
print(x9 % 3)
print(x9 / 3)

In [ ]:
print(x9)
print(x9.sum())
print(x9.sum(0))
print(x9.sum(1))

In [ ]:
print(x9)
print(x9.max())
print()
print(x9.max(0))
print()
print(x9.max(1))

In [ ]:
print(x9)
print(x9.min())
print()
print(x9.min(0))
print()
print(x9.min(1))

In [ ]:
x10 = torch.tensor([[-1, -2], [3, 4]])
x10

In [ ]:
x10.abs()

In [ ]:
x10[1] = torch.Tensor([3, 10])
x10

In [ ]:
value, index = x10.max(dim = 0)
value, index

In [ ]:
value, index = x10.max(dim = 1)
value, index

In [ ]:
x10.max()


# 행렬 연산

In [ ]:
x11 = torch.randn(3,5)
x12 = torch.randn(5,5)
x13 = torch.randn(5,3)
x11, x12, x13

In [ ]:
# scalar 연산
1.6200 * 1.1375  + 0.3436 * -0.9347 + -0.9112 * 1.3267 + -0.9952 *  -0.0336 + 0.7455 * 1.3210

In [ ]:
# 행렬 연산
# matrix-matrix
torch.mm(x11,x12), x11.mm(x12)

In [ ]:
# matrix-matrix
x11.mm(x12).mm(x13)

In [ ]:
x11.mm(x12).mm(x13).mm(x11)

In [ ]:
x14 = torch.randn(3, 4)
v = torch.randn(4)

x14, v

In [ ]:
-0.4594 * 0.6623 + -1.1798 * 0.2916 +0.3812 * 0.0409+ -0.0064 *  -1.1908

In [ ]:
# # matrix-vector = mv
torch.mv(x14,v), x14.mv(v)

In [ ]:
x15 = torch.randn(10,3,4)
x16 = torch.randn(10,4,5)

# batch matrix-matrix product
# (10,3,4).(10,4,5) => (10,3,5)
torch.bmm(x15, x16).size()

In [ ]:
torch.bmm(x15, x16)

In [ ]:
x17 = torch.randn(2,2)
x18 = torch.randn(2,2)

print(x17)
print(x18)


In [ ]:
print(x17.view(-1))
print(x18.view(-1))

In [ ]:
# Computes the dot product (inner product) of two tensors.
# 내적
torch.dot(x17.view(-1), x18.view(-1))

In [ ]:
x19  = torch.rand(3,4)

print(x19)
print(x19.size())
print()
print(x19.t())
print(x19.t().size())

In [ ]:
# distane (norm)
x1 = torch.tensor([1., 1.])
x2 = torch.tensor([5, 5.])

torch.dist(x1, x2, 2)
torch.dist(x1, x2, 2)**2

## Tensor Data Type

In [ ]:
x20 = torch.rand(2,2)
x20

In [ ]:
x20  = torch.LongTensor([1,1])
x20

In [ ]:
x20.float()

In [ ]:
x20.double()

In [ ]:
x20.byte()

In [ ]:
x20

In [ ]:
# GPU -> CPU
x20 = x20.cpu()
x20

In [ ]:
# to numpy
x20.numpy()

In [ ]:
torch.from_numpy(np.random.rand(3,2))