## 학습데이터 준비하기 - p.61

In [2]:
import torch
# from torch.autograd import Variable # Deprecated -> Torch에 지원
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset # DataLoader, TensorDataset

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

import pandas as pd

In [3]:
wine = load_wine()
wine.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [4]:
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df.head(3)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0

In [9]:
df.shape

(178, 13)

In [10]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [11]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [12]:
wine_data = wine.data[:130]
wine_data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.179e+01, 2.130e+00, 2.780e+00, ..., 9.700e-01, 2.440e+00,
        4.660e+02],
       [1.237e+01, 1.630e+00, 2.300e+00, ..., 8.900e-01, 2.780e+00,
        3.420e+02],
       [1.204e+01, 4.300e+00, 2.380e+00, ..., 7.900e-01, 2.570e+00,
        5.800e+02]])

In [80]:
wine_target = wine.target[:130]
wine_target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [117]:
train_X, test_X, train_y, test_y = train_test_split(wine_data, wine_target, test_size=.2)

In [118]:
print(train_X.shape)
print(test_X.shape)

(104, 13)
(26, 13)


## 텐서 생성 - P.64

In [119]:
# This is the Code
# tensor from numpy
train_X = torch.from_numpy(train_X).float() # double(float64)->float(float32)
train_y = torch.from_numpy(train_y).long() # long -> long (int64)

In [120]:
test_X = torch.from_numpy(test_X).float()
test_y = torch.from_numpy(test_y).long()

In [121]:
print(train_X.size()) # ->104행 13열 (2차원배열)
print(train_y.size()) # ->104개  (1차원배열)

torch.Size([104, 13])
torch.Size([104])


In [122]:
# This is the Code
train = TensorDataset(train_X, train_y) # like Dataframe

In [123]:
train

In [124]:
train.tensors

(tensor([[1.1870e+01, 4.3100e+00, 2.3900e+00,  ..., 7.5000e-01, 3.6400e+00,
          3.8000e+02],
         [1.3300e+01, 1.7200e+00, 2.1400e+00,  ..., 1.0200e+00, 2.7700e+00,
          1.2850e+03],
         [1.1640e+01, 2.0600e+00, 2.4600e+00,  ..., 1.0000e+00, 2.7500e+00,
          6.8000e+02],
         ...,
         [1.2000e+01, 1.5100e+00, 2.4200e+00,  ..., 1.0500e+00, 2.6500e+00,
          4.5000e+02],
         [1.1650e+01, 1.6700e+00, 2.6200e+00,  ..., 1.3600e+00, 3.2100e+00,
          5.6200e+02],
         [1.2990e+01, 1.6700e+00, 2.6000e+00,  ..., 1.3100e+00, 3.5000e+00,
          9.8500e+02]]),
 tensor([1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
         0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
         1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
         0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
         1, 0, 1, 0, 1, 1, 1, 1]))

In [125]:
print("train_X", train.tensors[0].size())
print("train_y", train.tensors[1].size())

train_X torch.Size([104, 13])
train_y torch.Size([104])


In [126]:
# This is the Code
train_loader = DataLoader(train, batch_size=16, shuffle=True) 
train_loader

## 신경망 구성 - P.67

In [127]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(13, 96) # 입력층 - 중간층
        self.fc2 = nn.Linear(96, 2)  # 중간층 - 출력층
        
    def forward(self, x):
        # forward propagation - FP
        x = self.fc1(x)
        x = F.relu(x) # 중간층 - Activate Function 
        
        x = self.fc2(x)
        # Classification Problem
        return F.log_softmax(x, dim=1) # 출력층 - Activate Function 
        # return F.log_softmax(x, dim=None)

In [128]:
model = Net()

## 모형 학습 - P.69

In [129]:
# Cross Entropy Loss(Cost) Function
criterion = nn.CrossEntropyLoss()
# metric = nn.CrossEntropyLoss()

In [130]:
# Stochastic Gradient Decent
optimizer = optim.SGD(model.parameters(), lr=0.01) # learning late

In [131]:
for epoch in range(300):
    total_loss = 0
    
    for train_x, train_y in train_loader:
        # train_x, train_y = Variable(train_x), Variable(train_y) # Deprecated
        
        optimizer.zero_grad() # reset gradient
        
        output = model(train_x)
        
        loss = criterion(output, train_y)
        
        loss.backward()
        
        optimizer.step()
        
        # total_loss += loss.data[0]
        total_loss += loss.item()
    if (epoch+1) % 50 == 0:
        print(epoch+1, total_loss)
        print("="*40)

50 4.849838376045227
100 4.8507556319236755
150 4.858715534210205
200 4.828313171863556
250 4.835828244686127
300 4.8360594511032104


In [132]:
type(test_X)

torch.Tensor

In [134]:
# 출력이 0 혹은 1이 되게 함
result = torch.max(model(test_X), 1)[1]
# result = torch.max(model(test_X), 1).indices

#정확도 측정
accuracy = sum(test_y.data.numpy() == result.numpy()) / len(test_y.data.numpy())
accuracy

0.6153846153846154

In [133]:
torch.max(model(test_X), 1)

(tensor([-0.6375, -0.6375, -0.6375, -0.6375, -0.6375, -0.6375, -0.6375, -0.6375,
         -0.6375, -0.6375, -0.6375, -0.6375, -0.6375, -0.6375, -0.6375, -0.6375,
         -0.6375, -0.6375, -0.6375, -0.6375, -0.6375, -0.6375, -0.6375, -0.6375,
         -0.6375, -0.6375], grad_fn=<MaxBackward0>),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1]))