## 학습데이터 준비하기 - p.61

In [269]:
import torch
from torch.autograd import Variable # Deprecated -> Torch에 지원
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset # DataLoader, TensorDataset

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

import pandas as pd

In [270]:
wine = load_wine()
wine.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [271]:
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df.head(3)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0

In [272]:
df.shape

(178, 13)

In [273]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [274]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [275]:
wine_data = wine.data[:130]
wine_data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.179e+01, 2.130e+00, 2.780e+00, ..., 9.700e-01, 2.440e+00,
        4.660e+02],
       [1.237e+01, 1.630e+00, 2.300e+00, ..., 8.900e-01, 2.780e+00,
        3.420e+02],
       [1.204e+01, 4.300e+00, 2.380e+00, ..., 7.900e-01, 2.570e+00,
        5.800e+02]])

In [276]:
wine_target = wine.target[:130]
wine_target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [277]:
train_X, test_X, train_y, test_y = train_test_split(wine_data, wine_target, test_size=.2)

In [278]:
print(train_X.shape)
print(test_X.shape)

(104, 13)
(26, 13)


## 텐서 생성 - P.64

In [279]:
# This is the Code
# tensor from numpy
train_X = torch.from_numpy(train_X).float() # double(float64)->float(float32)
train_y = torch.from_numpy(train_y) # long -> long (int64)

In [280]:
test_X = torch.from_numpy(test_X).float()
test_y = torch.from_numpy(test_y) 

In [281]:
print(train_X.size()) # ->104행 13열 (2차원배열)
print(train_y.size()) # ->104행 1열  (1차원배열)

torch.Size([104, 13])
torch.Size([104])


In [282]:
# This is the Code
train = TensorDataset(train_X, train_y) # like Dataframe

In [283]:
train

In [284]:
train.tensors

(tensor([[1.3240e+01, 3.9800e+00, 2.2900e+00,  ..., 8.2000e-01, 3.0000e+00,
          6.8000e+02],
         [1.1840e+01, 8.9000e-01, 2.5800e+00,  ..., 7.9000e-01, 3.0800e+00,
          5.2000e+02],
         [1.2520e+01, 2.4300e+00, 2.1700e+00,  ..., 9.0000e-01, 2.7800e+00,
          3.2500e+02],
         ...,
         [1.2370e+01, 1.0700e+00, 2.1000e+00,  ..., 1.0400e+00, 2.7700e+00,
          6.6000e+02],
         [1.3280e+01, 1.6400e+00, 2.8400e+00,  ..., 1.0900e+00, 2.7800e+00,
          8.8000e+02],
         [1.2290e+01, 3.1700e+00, 2.2100e+00,  ..., 1.4200e+00, 2.8300e+00,
          4.0600e+02]]),
 tensor([0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
         0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
         0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
         1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
         1, 1, 0, 1, 1, 1, 0, 1]))

In [285]:
print("train_X", train.tensors[0].size())
print("train_y", train.tensors[1].size())

train_X torch.Size([104, 13])
train_y torch.Size([104])


In [286]:
# This is the Code
train_loader = DataLoader(train, batch_size=16, shuffle=True) 
train_loader

## 신경망 구성 - P.67

In [287]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(13, 96) # 입력층 - 중간층
        self.fc2 = nn.Linear(96, 2)  # 중간층 - 출력층
        
    def forward(self, x):
        # forward propagation - FP
        x = F.relu(self.fc1(x)) # 중간층 - Activate Function 
        x = self.fc2(x)
        # Classification Problem
        return F.log_softmax(x, dim=1) # 출력층 - Activate Function 
        # return F.log_softmax(x, dim=None)

In [288]:
model = Net()

## 모형 학습 - P.69

In [289]:
# Cross Entropy Loss(Cost) Function
criterion = nn.CrossEntropyLoss()
# metric = nn.CrossEntropyLoss()

In [290]:
# Stochastic Gradient Decent
optimizer = optim.SGD(model.parameters(), lr=0.01) # learning late

In [291]:
for epoch in range(300):
    total_loss = 0
    
    for train_x, train_y in train_loader:
        # train_x, train_y = Variable(train_x), Variable(train_y) # Deprecated
        
        optimizer.zero_grad() # reset gradient
        
        output = model(train_x)
        
        loss = criterion(output, train_y)
        
        loss.backward()
        
        optimizer.step()
        
        # total_loss += loss.data[0]
        total_loss += loss.item()
    if (epoch+1) % 50 == 0:
        print(epoch+1, total_loss)
        print("="*40)

50 4.821952819824219
100 4.827742874622345
150 4.835538625717163
200 4.843066096305847
250 4.8360119462013245
300 4.850306510925293


In [292]:
type(test_X)

torch.Tensor

In [294]:
# 출력이 0 혹은 1이 되게 함
# result = torch.max(model(test_X), 1)[1]
result = torch.max(model(test_X), 1).indices

#정확도 측정
accuracy = sum(test_y.data.numpy() == result.numpy()) / len(test_y.data.numpy())
accuracy

0.6153846153846154