# 1. Tensor

In [4]:
import torch

In [5]:
print(torch.__version__)

1.1.0.post2


## 1.1 Tensor Basic

In [6]:
#Tensor의 기초적 선언
#torch.FloatTensor와 같음
# x = torch.Tensor(행, 열)
x = torch.Tensor(2, 3)
print(x)

tensor([[ 1.0232e-04, -2.5250e-29,  0.0000e+00],
        [-1.0842e-19,  5.6052e-45,  0.0000e+00]])


In [7]:
#Tesnor의 정보 확인
print("Tensor Type : ", type(x))
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size()) # = x.shape

Tensor Type :  <class 'torch.Tensor'>
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [8]:
y = torch.IntTensor(2, 4)
print(y)

tensor([[          0,           0,           0,           0],
        [          0, -1610612736,           0, -1610612736]],
       dtype=torch.int32)


In [9]:
#Tesnor의 정보 확인
print("Tensor Type : ", type(y))
print("Tensor Type : ", y.type())
print("Tensor Size : ", y.size()) # = x.shape

Tensor Type :  <class 'torch.Tensor'>
Tensor Type :  torch.IntTensor
Tensor Size :  torch.Size([2, 4])


## 1.2 특별한 Tensor

In [10]:
#0으로 채워진 Tensor 선언
x = torch.zeros(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [12]:
x = torch.zeros(2,3, dtype=torch.int32)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
Tensor Type :  torch.IntTensor
Tensor Size :  torch.Size([2, 3])


In [13]:
#1로 채워진 Tensor 선언
x = torch.ones(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [15]:
#0, 1 사이의 랜덤 숫자로 채워진 Tensor 선언
x = torch.rand(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0.5932, 0.7755, 0.0917],
        [0.9692, 0.3949, 0.3468]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [17]:
#평균이 0이고 분산이 1을 따르는 정규분포에서 추출된 값으로 채워진 Tensor 선언
x = torch.randn(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[-0.8686, -0.4747,  0.7151],
        [ 1.1404,  0.1891,  0.0408]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [21]:
#단위행렬과 같은 Tensor 선언
x = torch.eye(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 0., 0.],
        [0., 1., 0.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [25]:
#0부터 2까지 0.5씩 증가하는 Tensor 선언

x = torch.arange(0, 2, 0.5)
# x = torch.arange(0, 2, step=0.5)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([0.0000, 0.5000, 1.0000, 1.5000])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([4])


In [28]:
#직접 값을 입력하여 선언
x = torch.Tensor([[1,2,3],[1,2,3]])
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [29]:
#32-bit floating point
x = torch.FloatTensor(2,3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[ 0.0000e+00, -1.0842e-19,  0.0000e+00],
        [-1.0842e-19,  8.4078e-45,  0.0000e+00]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [30]:
#32-bit integer (signed)
x = torch.IntTensor(2,3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
Tensor Type :  torch.IntTensor
Tensor Size :  torch.Size([2, 3])


## 1.3 브릿지 Tensor & Numpy

In [45]:
import numpy as np

In [46]:
#numpy 형식의 배열
x = np.array([[1,2,3],[1,2,3]])
print(x, type(x))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


In [47]:
#numpy를 tensor로 변환
y = torch.from_numpy(x) # x = torch.Tensor(x)
print(y)
print("Tensor Type : ", y.type())
print("Tensor Size : ", y.size())

tensor([[1, 2, 3],
        [1, 2, 3]])
Tensor Type :  torch.LongTensor
Tensor Size :  torch.Size([2, 3])


In [48]:
#tensor를 numpy로 변환
z = y.numpy()
print(x, type(x))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


## 1.4 Tensor Slicing

In [49]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [50]:
#모든 원소 출력
x[:, :]

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [51]:
#2행부터 출력
x[1:, :]

tensor([[ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [52]:
#2열부터 출력
x[:, 1:]

tensor([[ 2.,  3.,  4.],
        [ 6.,  7.,  8.],
        [10., 11., 12.]])

In [53]:
#2행, 2열부터 3열까지 출력
x[1:, 1:3]

tensor([[ 6.,  7.],
        [10., 11.]])

In [54]:
#1행 출력
x[0, :]

tensor([1., 2., 3., 4.])

In [65]:
#x를 1행씩 잘라서 배열의 Tuple로 저장
x_rows = torch.split(x, split_size_or_sections=1, dim=0)
print(x_rows)

(tensor([[1., 2., 3., 4.]]), tensor([[5., 6., 7., 8.]]), tensor([[ 9., 10., 11., 12.]]))


In [66]:
#x를 2열씩 잘라서 배열의 Tuple로 저장
x_cols = torch.split(x, split_size_or_sections=2, dim=1)
print(x_cols)

(tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]]), tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]))


In [68]:
#위와 같은 결과
torch.chunk(x, chunks=2, dim=1)

(tensor([[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]]), tensor([[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]))

In [71]:
#x_cols의 첫번째 배열 중 특정 부분만 추출하기
torch.masked_select(x_cols[0], torch.ByteTensor([[0,1],[1,0],[0,1]]))

tensor([ 2.,  5., 10.])

## 1.5 Tensor 합치기

#### cat: 차원 유지

In [117]:
x_rows

(tensor([[1., 2., 3., 4.]]),
 tensor([[5., 6., 7., 8.]]),
 tensor([[ 9., 10., 11., 12.]]))

In [118]:
#x_rows를 행으로 이어 붙이기
torch.cat(x_rows, dim=0) # dim: axis와 같음 

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [119]:
#x_rows를 열로 이어 붙이기
torch.cat(x_rows, dim=1) # dim: axis와 같음 

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [120]:
x_cols

(tensor([[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]]), tensor([[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]))

In [121]:
x_col1, x_col2 = x_cols

In [122]:
print(x_col1, x_col2, sep='\n')

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])
tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]])


#### Stack: 차원 확대

In [123]:
#x_cols를 쌓아올리기
x_new = torch.stack([x_col1, x_col2], dim=0) # dim: axis와 같음 
print(x_new)
print(x_new.size())

tensor([[[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]],

        [[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]])
torch.Size([2, 3, 2])


In [124]:
#x_cols를 쌓아올리기
x_new = torch.stack([x_col1, x_col2], dim=1) # dim: axis와 같음 
print(x_new)
print(x_new.size())

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
torch.Size([3, 2, 2])


## 1.6 Tensor Reshaping

In [127]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [133]:
#4행 3열로 바꾸기 # reshpae과 같음
x.view(4, 3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [134]:
#2열로 바꾸기
x.view(-1, 2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [145]:
y = x.view(2, 1, -1)
print(y)
print("Size:", y.size())

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])
Size: torch.Size([2, 1, 6])


In [146]:
#차원이 1인 값을 축소
y = x.view(2, 1, -1).squeeze()
print(y)
print("Size:", y.size())

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])
Size: torch.Size([2, 6])


In [159]:
#dim=1 자리에 차원을 추가
y = x.view(2, 1, -1).squeeze().unsqueeze(dim=1)
print(y)
print("Size:", y.size())

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])
Size: torch.Size([2, 1, 6])


In [162]:
#dim=2 자리에 차원을 추가 (차원)
y = x.view(2, 1, -1).squeeze().unsqueeze(dim=2)
print(y)
print("Size:", y.size())

tensor([[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.]],

        [[ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.]]])
Size: torch.Size([2, 6, 1])


## 1.7 GPU를 위한 Tensor - Cuda
#### CUDA(Computed Unified Device Architecture)
#### NVIDIA만 가능

In [172]:
x = torch.Tensor([[1,2,3],[1,2,3]])
print(x)

tensor([[1., 2., 3.],
        [1., 2., 3.]])


In [173]:
# cuda 확인
print("현재 Cuda 사용 가능한 Device 개수 :", torch.cuda.device_count())
print("현재 Cuda 사용 가능 여부 :", torch.cuda.is_available())
print("현재 사용 중인 Cuda Device :", torch.cuda.current_device())
print("현재 Cuda Device 이름 :", torch.cuda.get_device_name(0))
print("현재 Cuda Device의 사용 가능한 메모리 :", torch.cuda.max_memory_allocated(device=0), "bytes")
print("현재 Cuda Device의 사용 중인 메모리 :", torch.cuda.memory_allocated(device=0), "bytes")

현재 Cuda 사용 가능한 Device 개수 : 0
현재 Cuda 사용 가능 여부 : False


AssertionError: Torch not compiled with CUDA enabled

In [174]:
# cuda 세팅
torch.cuda.set_device(0)

AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

In [175]:
#cpu를 gpu로 전환
gpu_x = x.cuda()
print(gpu_x)
print("Tensor Type : ", gpu_x.type())
print("Tensor Size : ", gpu_x.size())

AssertionError: Torch not compiled with CUDA enabled

In [176]:
#cpu를 gpu로 전환 2
device = torch.device("cuda")
gpu_x = x.to(device)
print(gpu_x)
print("Tensor Type : ", gpu_x.type())
print("Tensor Size : ", gpu_x.size())

AssertionError: Torch not compiled with CUDA enabled

In [177]:
#gpu를 cpu로 전환
x = gpu_x.cpu()
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

NameError: name 'gpu_x' is not defined

In [178]:
#gpu를 cpu로 전환 2
device = torch.device("cpu")
x = gpu_x.to(device)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

NameError: name 'gpu_x' is not defined

In [179]:
# gpu tensor와 cpu tensor의 연산
gpu_x + x

NameError: name 'gpu_x' is not defined

## 1.8 Tensor 연산

In [180]:
x = torch.Tensor([[1,2,3],[4,5,6]])
y = torch.Tensor([[1,1,1],[2,2,2]])
print("x :", x)
print("y :", y)

x : tensor([[1., 2., 3.],
        [4., 5., 6.]])
y : tensor([[1., 1., 1.],
        [2., 2., 2.]])


In [181]:
# x와 y의 합
z = torch.add(x, y)
print("z :", z)
print("x+y :", x+y)

z : tensor([[2., 3., 4.],
        [6., 7., 8.]])
x+y : tensor([[2., 3., 4.],
        [6., 7., 8.]])


In [186]:
# x의 모든 원소에서 2를 뺌
print(x - 2)

# x의 모든 원소에 2를 곱함
print(2*x)

tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [187]:
#x의 원소와 y의 원소를 각각 곱함
z = torch.mul(x, y)
print("z :", z)
print("x*y :", x*y)

z : tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])
x*y : tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])


In [188]:
#x의 원소를 각각 제곱함
z = torch.pow(x, 2)
print("z :", z)
print("x**2 :", x**2)

z : tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
x**2 : tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


In [189]:
#x의 원소에 log를 씌움
z = torch.log(x)
print("z :", z)
print("x.log() :", x.log())

z : tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
x.log() : tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])


In [190]:
#x의 원소에 루트를 씌움
z = torch.sqrt(x)
print("z :", z)
print("x.sqrt() :", x.sqrt())

z : tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])
x.sqrt() : tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])


In [191]:
#x의 원소에 나머지(mod) 계산
z = x % 2
print(z)

tensor([[1., 0., 1.],
        [0., 1., 0.]])


In [192]:
#x에 절댓값
z = torch.abs(x)
print("z :", z)
print("x.abs() :", x.abs())

z : tensor([[1., 2., 3.],
        [4., 5., 6.]])
x.abs() : tensor([[1., 2., 3.],
        [4., 5., 6.]])


## 1.9 Tensor 타입변환(Casting)

In [193]:
x = torch.Tensor([[1,2,3],[4,5,6]])
y = torch.Tensor([[1,1,1],[2,2,2]])
print("x :", x)
print("y :", y)

x : tensor([[1., 2., 3.],
        [4., 5., 6.]])
y : tensor([[1., 1., 1.],
        [2., 2., 2.]])


In [194]:
x.type(torch.DoubleTensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [195]:
x.double()

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [196]:
x.type(torch.IntTensor)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [197]:
x.int()

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

## 1.10 Tensor 통계연산(Statistic)

In [204]:
x = torch.Tensor([[-1,2,-3],[4,-5,6]])
print(x)

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])


In [205]:
print("x의 합 :", x.sum())
print("x의 최대값 :", x.max())
print("x의 최소값 :", x.min())
print("x의 분산 :", x.var())

x의 합 : tensor(3.)
x의 최대값 : tensor(6.)
x의 최소값 : tensor(-5.)
x의 분산 : tensor(17.9000)


In [207]:
# Scalar Tensor
# scalar는 차원이 없음
x.sum().size() 

torch.Size([])

In [208]:
# item의 활용
print("x의 합 :", x.sum().item())
print("x의 최대값 :", x.max().item())
print("x의 최소값 :", x.min().item())
print("x의 분산 :", x.var().item())

x의 합 : 3.0
x의 최대값 : 6.0
x의 최소값 : -5.0
x의 분산 : 17.899999618530273


In [216]:
#행을 기준으로 열의 최댓값을 출력
value, index = x.max(dim=0)
value

tensor([4., 2., 6.])

In [217]:
#열을 기준으로 행의 최댓값을 출력
x.max(dim=1)

torch.return_types.max(
values=tensor([2., 6.]),
indices=tensor([1, 2]))

In [219]:
#열을 기준으로 각 행을 정렬
value, index = x.sort(dim=1)
value

tensor([[-3., -1.,  2.],
        [-5.,  4.,  6.]])

## 1.11 Tensor function (*_like )
#### 모양이 같음

In [228]:
x = torch.Tensor([[-1,2,-3],[4,-5,6]])
print(x)

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])


In [229]:
y = torch.zeros_like(x)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [230]:
y = torch.ones_like(x)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [231]:
y = torch.rand_like(x)
print(y)

tensor([[0.7755, 0.9545, 0.2440],
        [0.2744, 0.0252, 0.7163]])


## 1.12 Tensor 행렬연산 

In [233]:
x = torch.Tensor([[1,1],[2,2]])
y = torch.Tensor([[1,2],[3,4]])
print("x :", x)
print("y :", y)

x : tensor([[1., 1.],
        [2., 2.]])
y : tensor([[1., 2.],
        [3., 4.]])


In [239]:
#x와 y의 행렬곱 - multiply matrix
torch.mm(x, y)

tensor([[ 4.,  6.],
        [ 8., 12.]])

In [240]:
#x와 z의 행렬벡터곱 - Multiply Vector
z = torch.Tensor([1, 2])
torch.mv(x, z)

tensor([3., 6.])

In [242]:
z

tensor([1., 2.])

In [254]:
#z와 z의 내적
torch.dot(z, z)

tensor(5.)

In [258]:
#x의 전치(transpose)
x.t()

tensor([[1., 2.],
        [1., 2.]])

In [259]:
# y의 역행렬(inverse)
y.inverse()

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])