In [2]:
import numpy as np

# 배열

## sequence 데이터로부터 배열 생성

#### range 배열 생성

In [3]:
data1 = range(10)
arr1 = np.array(data1)

arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### list 배열 생성
##### \*\*\* python 내장 List와 다르게 numpy 배열은  type을 통일시킴

In [4]:
data2 = [0.1, 5, 4, 12, 0.5]
arr2 = np.array(data2)

arr2 # 모두 실수로 변환


array([ 0.1,  5. ,  4. , 12. ,  0.5])

#### list 배열 생성 with random

In [5]:
import random


data3 = [random.uniform(-1, 1) for i in range(10)]
# print(f'data2 \n type={type(data2)}, \n content={data2}')
arr3 = np.array(data3)
arr3

array([-0.33019702, -0.51586011,  0.68689198, -0.24686018,  0.42898702,
        0.28691304, -0.60529434,  0.57169463,  0.40102128, -0.37114042])

#### 속성혼합

In [6]:
arr4 = np.array([1, 2, 'a', 'b', 1.0, 2.0])
arr4

array(['1', '2', 'a', 'b', '1.0', '2.0'], dtype='<U11')

### Numpy 다차원 배열

In [8]:
data5 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

arr5 = np.array(data5)
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### array 속성 확인

##### 데이터 타입 - dtype

In [9]:
arr1.dtype

dtype('int32')

In [10]:
arr2.dtype

dtype('float64')

In [11]:
arr3.dtype

dtype('float64')

In [12]:
arr4.dtype

dtype('<U11')

In [13]:
arr5.dtype

dtype('int32')

In [14]:
arr5.dtype.name

'int32'

#### 배열의 형태 알기 - shape

In [15]:
# 1차원 배열
arr2.shape

(5,)

In [16]:
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# 2차원 배열
arr5.shape

(3, 3)

## 범위를 지정해 배열 생성 - arange

In [18]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr2 = np.arange(5, 11)
arr2

array([ 5,  6,  7,  8,  9, 10])

In [20]:
arr3 = np.arange(5, 11, 2)
arr3

array([5, 7, 9])

In [21]:
arr4 = np.arange(5, 11, 2.0)
arr4

array([5., 7., 9.])

## linear한 배열 생성 - linspace

In [25]:
arr1 = np.linspace(1, 10, 5)
arr1


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [26]:
len(arr1)

5

In [27]:
arr2 = np.linspace(5, 200)
arr2
len(arr2)

50

In [28]:
arr1 = np.linspace(1, 200, 27)
arr1

array([  1.        ,   8.65384615,  16.30769231,  23.96153846,
        31.61538462,  39.26923077,  46.92307692,  54.57692308,
        62.23076923,  69.88461538,  77.53846154,  85.19230769,
        92.84615385, 100.5       , 108.15384615, 115.80769231,
       123.46153846, 131.11538462, 138.76923077, 146.42307692,
       154.07692308, 161.73076923, 169.38461538, 177.03846154,
       184.69230769, 192.34615385, 200.        ])

In [29]:
len(arr1)

27

In [ ]:
arr2 = np.linspace(5, 200)
arr2

In [ ]:
len(arr2)

In [ ]:
arr3 = np.linspace(0, np.pi, 20)
arr3

In [ ]:
len(arr3)

## 배열의 형태 변경 - reshape

In [30]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr2 = arr1.reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
arr3 = arr2.reshape(-1)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr2.reshape(-1, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [35]:
arr4 = np.arange(16).reshape(4,4)
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
arr4.shape = (2,8)
arr4

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [37]:
# 3차원 행렬
arr5 = np.arange(27).reshape(3,3,3)
arr5

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

## 배열의 데이터 타입 변환

In [38]:
data1 = ['1.5', '.62', '3.14', '3.141592']
str_arr = np.array(data1)
str_arr

array(['1.5', '.62', '3.14', '3.141592'], dtype='<U8')

##### float형

In [39]:
float_arr = str_arr.astype(float)
float_arr

array([1.5     , 0.62    , 3.14    , 3.141592])

In [40]:
float_arr.dtype

dtype('float64')

##### int형

In [41]:
int_arr = float_arr.astype(int)
int_arr

array([1, 0, 3, 3])

In [42]:
int_arr.dtype

dtype('int32')

##### unicode형

In [43]:
unicode_arr = int_arr.astype(str)
unicode_arr

array(['1', '0', '3', '3'], dtype='<U11')

In [44]:
unicode_arr.dtype

dtype('<U11')

##### 복소수형(complex)

In [46]:
complex_arr = float_arr.astype(complex)
complex_arr

array([1.5     +0.j, 0.62    +0.j, 3.14    +0.j, 3.141592+0.j])

In [47]:
complex_arr.dtype

dtype('complex128')

## 난수 배열의 생성

### rand함수

In [49]:
rand_float = np.random.rand()
rand_float

0.13282268417316667

In [51]:
rand_float_arr1 = np.random.rand(4)
rand_float_arr1

array([0.05649186, 0.77439378, 0.05547015, 0.6126649 ])

In [53]:
rand_float_arr1.shape

(4,)

In [57]:
rand_float_arr2 = np.random.rand(3,3)
rand_float_arr2

array([[0.53901047, 0.28243414, 0.29099313],
       [0.57031741, 0.33715289, 0.48518879],
       [0.5109553 , 0.91692285, 0.57751312]])

In [58]:
rand_float_arr2.shape

(3, 3)

In [60]:
rand_float_arr3 = np.random.rand(3,2,2)
rand_float_arr3

array([[[0.43125731, 0.39773053],
        [0.14115078, 0.71236902]],

       [[0.01850996, 0.02325917],
        [0.99166264, 0.24654447]],

       [[0.06902052, 0.50934454],
        [0.48245747, 0.04612206]]])

In [61]:
rand_float_arr3.shape

(3, 2, 2)

### 정수 난수를 생성하는 - randint

In [63]:
rand_int = np.random.randint(100)
rand_int

70

In [64]:
rand_int_arr1 = np.random.randint(100, size=(3,4))
rand_int_arr1

array([[ 9, 19, 27, 13],
       [36, 14, 67, 31],
       [19, 25, 11, 26]])

In [65]:
rand_int_arr1.shape

(3, 4)

In [68]:
rand_int_arr2 = np.random.randint(80, 100, size=(3,2,2))
rand_int_arr2

array([[[86, 99],
        [95, 88]],

       [[99, 93],
        [99, 92]],

       [[94, 84],
        [84, 89]]])

In [69]:
rand_int_arr2.shape

(3, 2, 2)

### 정규분포 샘플링 np.random.randn

In [71]:
rand_n_arr = np.random.randn(2,3)
rand_n_arr

array([[ 0.142853  ,  1.49338768, -0.38876471],
       [-1.10462695,  0.7133048 ,  0.20492038]])

# 배열의 인덱싱과 슬라이싱

In [72]:
arr1 = np.arange(0, 60, 10)
arr1

array([ 0, 10, 20, 30, 40, 50])

In [73]:
print(arr1[0])
print(arr1[1])
print(arr1[-1])

0
10
50


In [74]:
arr1[:4]

array([ 0, 10, 20, 30])

In [75]:
arr1[3:]

array([30, 40, 50])

In [76]:
arr1[::2]

array([ 0, 20, 40])

In [77]:
arr1[1] = 100
arr1

array([  0, 100,  20,  30,  40,  50])

In [78]:
arr1

array([  0, 100,  20,  30,  40,  50])

In [79]:
arr1[[1,4]]

array([100,  40])

### 2차원 배열 인덱싱 슬라이싱

In [80]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [81]:
arr1[1]

array([3, 4, 5])

In [82]:
arr1[1][1]

4

In [83]:
arr1[1][1] = 30
arr1

array([[ 0,  1,  2],
       [ 3, 30,  5],
       [ 6,  7,  8]])

In [84]:
arr1[0,2]

2

In [85]:
arr1

array([[ 0,  1,  2],
       [ 3, 30,  5],
       [ 6,  7,  8]])

In [86]:
arr1[0,2] = 10
arr1

array([[ 0,  1, 10],
       [ 3, 30,  5],
       [ 6,  7,  8]])

In [87]:
arr1[2] = [3, 3, 3]
arr1

array([[ 0,  1, 10],
       [ 3, 30,  5],
       [ 3,  3,  3]])

In [88]:
arr1[1:,1:] 

array([[30,  5],
       [ 3,  3]])

In [89]:
arr1[1:,1:] = np.array([[1,2],[3,4]])
arr1

array([[ 0,  1, 10],
       [ 3,  1,  2],
       [ 3,  3,  4]])

### 조건으로 인덱싱 슬라이싱

In [90]:
arr1 = np.arange(10,100,10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [91]:
arr1>50

array([False, False, False, False, False,  True,  True,  True,  True])

In [93]:
condition = \
np.array([False, False, False, False, False,  True,  True,  True,  True])

In [94]:
arr1[condition]

array([60, 70, 80, 90])

In [95]:
arr1[arr1>50]

array([60, 70, 80, 90])

In [96]:
arr2 = np.arange(10,100,10).reshape(3, 3)
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [97]:
arr2[arr2%4 == 0]

array([20, 40, 60, 80])

In [98]:
arr2[:-1:2, ::2]

array([[10, 30]])

## NaN (not a number) & Inf(Infinity)

In [99]:
import numpy as np

In [100]:
np.nan

arr1 = np.array([1,2,3, np.nan, np.inf])
arr1

array([ 1.,  2.,  3., nan, inf])

In [101]:
arr1.dtype

dtype('float64')

## 특별한 형태의 배열 생성

In [102]:
arr_zero_n = np.zeros(9)
arr_zero_n

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [103]:
arr_zero_mxn = np.zeros((3,3))
arr_zero_mxn

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [104]:
arr_one_n = np.ones(9)
arr_one_n

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [105]:
arr_one_mxn = np.ones((3,3))
arr_one_mxn

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [106]:
arr_I = np.eye(5)
arr_I

# X.dot(I) = X 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [107]:
arr_I2 = np.identity(5)
arr_I2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 배열의 연산

In [108]:
arr1 = np.arange(1.0,7)
arr2 = np.arange(10.0,70,10)

print('arr1: %s \t shape:%s' % (repr(arr1), arr1.shape))
print('arr2: %s \t shape:%s' % (repr(arr2), arr2.shape))



arr1: array([1., 2., 3., 4., 5., 6.]) 	 shape:(6,)
arr2: array([10., 20., 30., 40., 50., 60.]) 	 shape:(6,)


### 배열의 덧셈

In [109]:
arr1 + 100

array([101., 102., 103., 104., 105., 106.])

In [110]:
arr1 + arr2

array([11., 22., 33., 44., 55., 66.])

### 배열의 뺄셈

In [111]:
arr1 - 5

array([-4., -3., -2., -1.,  0.,  1.])

In [112]:
arr1 - arr2

array([ -9., -18., -27., -36., -45., -54.])

### 배열의 곱셈

In [113]:
arr1 * 5

array([ 5., 10., 15., 20., 25., 30.])

In [114]:
arr1 * arr2

array([ 10.,  40.,  90., 160., 250., 360.])

### 배열의 나눗셈

In [115]:
arr1 / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        ])

In [116]:
arr1 / arr2

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

### 배열의 거듭제곱

In [117]:
arr1 ** 2

array([ 1.,  4.,  9., 16., 25., 36.])

In [118]:
arr1 ** arr2

array([1.00000000e+00, 1.04857600e+06, 2.05891132e+14, 1.20892582e+24,
       8.88178420e+34, 4.88736780e+46])

### 배열의 복합연산

In [119]:
(arr1 + 100) / arr2

array([10.1       ,  5.1       ,  3.43333333,  2.6       ,  2.1       ,
        1.76666667])

### 배열의 비교연산

In [120]:
arr2 > 20

array([False, False,  True,  True,  True,  True])

## 다차원 배열에서의 연산

In [121]:
arr1 = np.arange(1,9).reshape(2,4)

arr2 = np.arange(10,90,10).reshape(2,4)

print('arr1: %s \t\t shape:%s' % (repr(arr1), arr1.shape))
print('arr2: %s \t shape:%s' % (repr(arr2), arr2.shape))

arr1: array([[1, 2, 3, 4],
       [5, 6, 7, 8]]) 		 shape:(2, 4)
arr2: array([[10, 20, 30, 40],
       [50, 60, 70, 80]]) 	 shape:(2, 4)


In [122]:
arr1*arr2 

array([[ 10,  40,  90, 160],
       [250, 360, 490, 640]])

## 통계를 위한 연산

### sum - 합 / mean - 평균

In [123]:
arr1 = np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
arr1.sum()

66

In [125]:
arr1.sum(axis=0)

array([12, 15, 18, 21])

In [126]:
arr1.sum(axis=1)

array([ 6, 22, 38])

In [127]:
arr1.mean()

5.5

In [128]:
arr1.mean(axis=0)

array([4., 5., 6., 7.])

In [129]:
arr1.mean(axis=1)

array([1.5, 5.5, 9.5])

### std - 표준편차 / var - 분산

In [130]:
arr1.std()

3.452052529534663

In [131]:
arr1.var()

11.916666666666666

In [132]:
np.sqrt(arr1.var())

3.452052529534663

In [133]:
arr1.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [134]:
arr1.var(axis=0)

array([10.66666667, 10.66666667, 10.66666667, 10.66666667])

In [135]:
np.sqrt(arr1.var(axis=0))

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [136]:
arr1.std(axis=1)

array([1.11803399, 1.11803399, 1.11803399])

In [137]:
arr1.var(axis=1)

array([1.25, 1.25, 1.25])

In [138]:
np.sqrt(arr1.var(axis=1))

array([1.11803399, 1.11803399, 1.11803399])

### min - 최소값 / max - 최대값

In [139]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [140]:
arr1.min(), arr1.max()

(0, 11)

In [141]:
arr1.min(axis=0)

array([0, 1, 2, 3])

In [142]:
arr1.min(axis=1)

array([0, 4, 8])

In [143]:
arr1.max(axis=0)

array([ 8,  9, 10, 11])

In [144]:
arr1.max(axis=1)

array([ 3,  7, 11])

### cumsum - 누적합 / cumprod - 누적곱

In [145]:
arr1 +=1
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [146]:
arr1.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78], dtype=int32)

In [147]:
arr1.cumsum(axis=0)

array([[ 1,  2,  3,  4],
       [ 6,  8, 10, 12],
       [15, 18, 21, 24]], dtype=int32)

In [150]:
arr1.cumsum(axis=1)

array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26],
       [ 9, 19, 30, 42]], dtype=int32)

In [151]:
arr1.cumprod()

array([        1,         2,         6,        24,       120,       720,
            5040,     40320,    362880,   3628800,  39916800, 479001600],
      dtype=int32)

In [152]:
arr1.cumprod(axis=0)

array([[  1,   2,   3,   4],
       [  5,  12,  21,  32],
       [ 45, 120, 231, 384]], dtype=int32)

In [153]:
arr1.cumprod(axis=1)

array([[    1,     2,     6,    24],
       [    5,    30,   210,  1680],
       [    9,    90,   990, 11880]], dtype=int32)

## 행렬 연산

In [155]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(6, 0, -1).reshape(3, 2)

print("A: %s" % repr(A))
print("B: %s" % repr(B))


A: array([[1, 2, 3],
       [4, 5, 6]])
B: array([[6, 5],
       [4, 3],
       [2, 1]])


### 행렬곱

In [156]:
A.dot(B)

array([[20, 14],
       [56, 41]])

In [157]:
np.dot(A,B)

array([[20, 14],
       [56, 41]])

In [158]:
B.dot(A)

array([[26, 37, 48],
       [16, 23, 30],
       [ 6,  9, 12]])

In [159]:
np.dot(B,A)

array([[26, 37, 48],
       [16, 23, 30],
       [ 6,  9, 12]])

### 전치행렬

In [160]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [161]:
A.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [162]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [163]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [164]:
B

array([[6, 5],
       [4, 3],
       [2, 1]])

In [165]:
B.transpose()

array([[6, 4, 2],
       [5, 3, 1]])

In [166]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [ ]:
np.transpose(B)

### 단위행렬

In [167]:
A = np.arange(1, 5).reshape(2, 2)
B = np.arange(4, 0, -1).reshape(2, 2)

print("A: %s" % repr(A))
print("B: %s" % repr(B))

A: array([[1, 2],
       [3, 4]])
B: array([[4, 3],
       [2, 1]])


In [168]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [169]:
A.dot(I)

array([[1., 2.],
       [3., 4.]])

In [170]:
B.dot(I)

array([[4., 3.],
       [2., 1.]])

### 역행렬

In [ ]:
# BA = I

In [173]:
A

array([[1, 2],
       [3, 4]])

In [174]:
B

array([[4, 3],
       [2, 1]])

In [175]:
Ai = np.linalg.inv(A)
Ai

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [176]:
# A.Ai = I
A.dot(Ai)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [177]:
Bi = np.linalg.inv(B)
Bi

array([[-0.5,  1.5],
       [ 1. , -2. ]])

In [178]:
B.dot(Bi)

array([[1., 0.],
       [0., 1.]])

### 행렬식

In [179]:
A

array([[1, 2],
       [3, 4]])

In [180]:
np.linalg.det(A)

-2.0000000000000004

In [181]:
np.linalg.det(B)

-2.0

# 배열의 인덱싱과 슬라이싱

In [ ]:
arr1 = np.arange(0, 60, 10)
arr1

In [ ]:
print(arr1[0])
print(arr1[1])
print(arr1[-1])

In [ ]:
arr1[:4]

In [ ]:
arr1[3:]

In [ ]:
arr1[::2]

In [ ]:
arr1[1] = 100
arr1

In [ ]:
arr1[[1,4]] # 1과 4 인덱스 가져오기

### 2차원 배열 인덱싱 슬라이싱

In [ ]:
arr1 = np.arange(9).reshape(3,3)
arr1

In [ ]:
arr1[1] # 1행 가져오기

In [ ]:
arr1[1][1] # 1행 1열 가져오기

In [ ]:
arr1[1][1] = 30
arr1

In [ ]:
arr1[0,2] # 0행 2열

In [ ]:
arr1[0,2] = 10
arr1

In [ ]:
arr1[2] = [3,3,3] # 열 전체 변경
arr1

In [ ]:
arr1[1:,1:] 

In [ ]:
arr1[1:,1:] = np.array([[1,2],[3,4]])
arr1

### 조건으로 인덱싱 슬라이싱

In [ ]:
arr1 = np.arange(10,100,10)
arr1

In [ ]:
arr1>50

In [ ]:
arr1[arr1>50]

In [ ]:
arr2 = np.arange(10,100,10).reshape(3, 3)
arr2

In [ ]:
arr2%4 == 0

In [ ]:
arr2[arr2%4 == 0]

## NaN (not a number) & Inf(Infinity)

In [ ]:
import numpy as np

In [ ]:
np.nan

arr1 = np.array([1,2,3, np.nan, np.inf, -np.inf])
arr1


# 다차원 연습하기

In [183]:
m = np.arange(18).reshape(3,2,3)

In [184]:
m

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [185]:
m[0,1,2]

5

In [186]:
m[2,1,1]

16

In [187]:
m[:,1,:]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17]])

In [188]:
m[2,:,:]

array([[12, 13, 14],
       [15, 16, 17]])

In [189]:
m[2, ...]

array([[12, 13, 14],
       [15, 16, 17]])

In [190]:
m[...,1]

array([[ 1,  4],
       [ 7, 10],
       [13, 16]])

In [191]:
m

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [192]:
for i in m:
    print(i)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[12 13 14]
 [15 16 17]]


In [193]:
m.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [194]:
m.flat

In [195]:
# m.flat: 차원을 펼쳐라.
for i in m.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


In [196]:
m.shape

(3, 2, 3)

In [197]:
# error가 됨.
m.reshape(2, 4) 

ValueError: cannot reshape array of size 18 into shape (2,4)

In [198]:
m.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [199]:
m.reshape(6,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [200]:
m.reshape(3,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [201]:
# 자체가 바뀜. == m.shape= 3,6
m.resize(3, 6)

In [202]:
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [203]:
m.shape= (3,6)

In [ ]:
m

### vstack

In [204]:
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [205]:
# 아래로 스택을 쌓음
# vertical stack
np.vstack((m,m)) 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [206]:
a = np.vstack((m, m, m))

In [207]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [208]:
i,j,k = np.vsplit(a, 3)

In [209]:
i

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [210]:
j

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [211]:
k

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [215]:
m = np.arange(9).reshape(3,3)

In [216]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [217]:
np.hstack((m, m))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [218]:
b = np.hstack((m, m, m))

In [219]:
b

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8, 6, 7, 8]])

In [220]:
i, j, k = np.hsplit(b, 3)

In [221]:
i

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [222]:
j

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [223]:
k

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [224]:
i == j

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [225]:
i is j # 완전이 같냐 = 주소까지 같냐

False

In [226]:
id(i)

105573232

In [227]:
id(j)

105574112

In [228]:
a = np.arange(10)

In [229]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [230]:
b = [x*2 for x in a if x % 2 == 0 ]

In [231]:
b

[0, 4, 8, 12, 16]

In [ ]:
dir(np)