In [2]:
import numpy as np

# 배열

## sequence 데이터로부터 배열 생성

#### range 배열 생성

In [18]:
data1 = range(10)
arr1 = np.array(data1)

arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### list 배열 생성
##### \*\*\* python 내장 List와 다르게 numpy 배열은  type을 통일시킴

In [19]:
data2 = [0.1, 5, 4, 12, 0.5]
arr2 = np.array(data2)

arr2 # 모두 실수로 변환


array([ 0.1,  5. ,  4. , 12. ,  0.5])

#### list 배열 생성 with random

In [20]:
import random


data3 = [random.uniform(-1, 1) for i in range(10)]
# print(f'data2 \n type={type(data2)}, \n content={data2}')
arr3 = np.array(data3)
arr3

array([ 0.70550234,  0.4364624 ,  0.45909271, -0.01648525, -0.42679034,
       -0.49771118, -0.19508723,  0.89203734, -0.50033416,  0.47302826])

#### 속성혼합

In [21]:
arr4 = np.array([1, 2, 'a', 'b', 1.0, 2.0])
arr4

array(['1', '2', 'a', 'b', '1.0', '2.0'], dtype='<U21')

### Numpy 다차원 배열

In [22]:
data5 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

arr5 = np.array(data5)
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### array 속성 확인

##### 데이터 타입 - dtype

In [23]:
arr1.dtype

dtype('int64')

In [24]:
arr2.dtype

dtype('float64')

In [25]:
arr3.dtype

dtype('float64')

In [26]:
arr4.dtype

dtype('<U21')

In [27]:
arr5.dtype

dtype('int64')

#### 배열의 형태 알기 - shape

In [33]:
# 1차원 배열
arr2.shape

(5,)

In [34]:
# 2차원 배열
arr5.shape

(3, 3)

## 범위를 지정해 배열 생성 - arange

In [92]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
arr2 = np.arange(5, 11)
arr2

array([ 5,  6,  7,  8,  9, 10])

In [35]:
arr3 = np.arange(5, 11, 2)
arr3

array([5, 7, 9])

In [36]:
arr4 = np.arange(5, 11, 2.0)
arr4

array([5., 7., 9.])

## linear한 배열 생성 - linspace

In [39]:
arr1 = np.linspace(1, 200, 27)
arr1


array([  1.        ,   8.65384615,  16.30769231,  23.96153846,
        31.61538462,  39.26923077,  46.92307692,  54.57692308,
        62.23076923,  69.88461538,  77.53846154,  85.19230769,
        92.84615385, 100.5       , 108.15384615, 115.80769231,
       123.46153846, 131.11538462, 138.76923077, 146.42307692,
       154.07692308, 161.73076923, 169.38461538, 177.03846154,
       184.69230769, 192.34615385, 200.        ])

In [41]:
len(arr1)

27

In [38]:
arr2 = np.linspace(5, 200)
arr2
len(arr2)

50

In [136]:
arr1 = np.linspace(1, 200, 27)
arr1

array([  1.        ,   8.65384615,  16.30769231,  23.96153846,
        31.61538462,  39.26923077,  46.92307692,  54.57692308,
        62.23076923,  69.88461538,  77.53846154,  85.19230769,
        92.84615385, 100.5       , 108.15384615, 115.80769231,
       123.46153846, 131.11538462, 138.76923077, 146.42307692,
       154.07692308, 161.73076923, 169.38461538, 177.03846154,
       184.69230769, 192.34615385, 200.        ])

In [141]:
len(arr1)

27

In [142]:
arr2 = np.linspace(5, 200)
arr2

array([  5.        ,   8.97959184,  12.95918367,  16.93877551,
        20.91836735,  24.89795918,  28.87755102,  32.85714286,
        36.83673469,  40.81632653,  44.79591837,  48.7755102 ,
        52.75510204,  56.73469388,  60.71428571,  64.69387755,
        68.67346939,  72.65306122,  76.63265306,  80.6122449 ,
        84.59183673,  88.57142857,  92.55102041,  96.53061224,
       100.51020408, 104.48979592, 108.46938776, 112.44897959,
       116.42857143, 120.40816327, 124.3877551 , 128.36734694,
       132.34693878, 136.32653061, 140.30612245, 144.28571429,
       148.26530612, 152.24489796, 156.2244898 , 160.20408163,
       164.18367347, 168.16326531, 172.14285714, 176.12244898,
       180.10204082, 184.08163265, 188.06122449, 192.04081633,
       196.02040816, 200.        ])

In [140]:
len(arr2)

50

In [144]:
arr3 = np.linspace(0, np.pi, 20)
arr3

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [145]:
len(arr3)

20

## 배열의 형태 변경 - reshape

In [55]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr2 = arr1.reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
arr3 = arr2.reshape(-1)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
arr4 = np.arange(16).reshape(4,4)
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [172]:
arr4.shape = (2,8)
arr4

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
# 3차원 행렬
arr5 = np.arange(27).reshape(3,3,3)
arr5

## 배열의 데이터 타입 변환

In [62]:
data1 = ['1.5', '.62', '3.14', '3.141592']
str_arr = np.array(data1)
str_arr

array(['1.5', '.62', '3.14', '3.141592'], dtype='<U8')

##### float형

In [60]:
float_arr = str_arr.astype(float)
float_arr

array([1.5     , 0.62    , 3.14    , 3.141592])

In [61]:
float_arr.dtype

dtype('float64')

##### int형

In [66]:
int_arr = float_arr.astype(int)
int_arr

array([1, 0, 3, 3])

In [67]:
int_arr.dtype

dtype('int64')

##### unicode형

In [89]:
unicode_arr = int_arr.astype(str)
unicode_arr

array([1, 0, 3, 3], dtype=uint64)

In [74]:
unicode_arr.dtype

dtype('int64')

##### 복소수형(complex)

In [139]:
complex_arr = float_arr.astype(complex)
complex_arr

array([ True,  True,  True,  True])

In [237]:
complex_arr.dtype

dtype('complex128')

## 난수 배열의 생성

### rand함수

In [242]:
rand_float = np.random.rand()
rand_float

0.35426100728807075

In [148]:
rand_float_arr1 = np.random.rand(4)
rand_float_arr1

array([0.97184509, 0.25078225, 0.05434848, 0.73020805])

array([[-0.54890223, -0.1501966 ,  0.80294757],
       [-0.97233412, -1.24891298, -0.32100883]])

In [251]:
rand_float_arr.shape

(4,)

In [143]:
rand_float_arr2 = np.random.rand(3,3)
rand_float_arr2

array([[0.55462646, 0.80164587, 0.54536984],
       [0.56789315, 0.94776571, 0.31523946],
       [0.02695779, 0.08999963, 0.64518168]])

In [254]:
rand_float_arr2.shape

(3, 3)

In [255]:
rand_float_arr3 = np.random.rand(3,3,5)
rand_float_arr3

array([[[0.31076459, 0.13012882, 0.77741743, 0.75029377, 0.87592642],
        [0.47880987, 0.49593741, 0.23475369, 0.54588437, 0.90380518],
        [0.48271576, 0.38661823, 0.18442423, 0.39931273, 0.64850719]],

       [[0.48773738, 0.56678455, 0.07996627, 0.39904493, 0.70047116],
        [0.75645142, 0.22165275, 0.54004684, 0.36102038, 0.12557512],
        [0.72811769, 0.10706826, 0.15601912, 0.98407265, 0.00343554]],

       [[0.24457353, 0.67557417, 0.73125695, 0.33451638, 0.49754299],
        [0.76407802, 0.7560957 , 0.54136424, 0.20825011, 0.09674473],
        [0.52281362, 0.13911197, 0.45951778, 0.27487141, 0.47595002]]])

In [256]:
rand_float_arr3.shape

(3, 3, 5)

### 정수 난수를 생성하는 - randint

In [262]:
rand_int = np.random.randint(100)
rand_int

64

In [269]:
rand_int_arr1 = np.random.randint(100, size=(3,4))
rand_int_arr1

array([[38, 24, 31, 86],
       [78, 11, 10, 14],
       [87, 54, 99, 53]])

In [270]:
rand_int_arr1.shape

(3, 4)

In [271]:
rand_int_arr2 = np.random.randint(80, 100, size=(3,3,3))
rand_int_arr2

array([[[80, 91, 89],
        [80, 95, 87],
        [86, 80, 82]],

       [[97, 96, 91],
        [90, 94, 91],
        [81, 97, 94]],

       [[96, 87, 84],
        [90, 84, 98],
        [81, 81, 81]]])

In [272]:
rand_int_arr2.shape

(3, 3, 3)

### 정규분포 샘플링 np.random.randn

In [ ]:
rand_n_arr = np.random.randn(2,3)
rand_n_arr

# 배열의 인덱싱과 슬라이싱

In [518]:
arr1 = np.arange(0, 60, 10)
arr1

array([ 0, 10, 20, 30, 40, 50])

In [519]:
print(arr1[0])
print(arr1[1])
print(arr1[-1])

0
10
50


In [520]:
arr1[:4]

array([ 0, 10, 20, 30])

In [521]:
arr1[3:]

array([30, 40, 50])

In [522]:
arr1[::2]

array([ 0, 20, 40])

In [523]:
arr1[1] = 100
arr1

array([  0, 100,  20,  30,  40,  50])

In [533]:
arr1[[1,4]]

array([100,  40])

### 2차원 배열 인덱싱 슬라이싱

In [535]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [538]:
arr1[1]

array([3, 4, 5])

In [553]:
arr1[1][1]

30

In [554]:
arr1[1][1] = 30
arr1

array([[ 0,  1, 10],
       [ 3, 30,  5],
       [ 6,  7,  8]])

In [555]:
arr1[0,2]

10

In [556]:
arr1[0,2] = 10
arr1

array([[ 0,  1, 10],
       [ 3, 30,  5],
       [ 6,  7,  8]])

In [581]:
arr1[2] = [3,3,3]
arr1

array([[10, 20, 30],
       [40, 50, 60],
       [ 3,  3,  3]])

In [582]:
arr1[1:,1:] 

array([[50, 60],
       [ 3,  3]])

In [587]:
arr1[1:,1:] = np.array([[1,2],[3,4]])
arr1

array([[10, 20, 30],
       [40,  1,  2],
       [ 3,  3,  4]])

### 조건으로 인덱싱 슬라이싱

In [7]:
arr1 = np.arange(10,100,10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
arr1[arr1>50]

array([60, 70, 80, 90])

In [9]:
arr2 = np.arange(10,100,10).reshape(3, 3)
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [10]:
arr2[arr2%4 == 0]

array([20, 40, 60, 80])

In [24]:
arr2[:-1:2, ::2]

array([[10, 30]])

## NaN (not a number) & Inf(Infinity)

In [1]:
import numpy as np

In [2]:
np.nan

arr1 = np.array([1,2,3, np.nan, np.inf])
arr1

array([ 1.,  2.,  3., nan, inf])

## 특별한 형태의 배열 생성

In [3]:
arr_zero_n = np.zeros(9)
arr_zero_n

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
arr_zero_mxn = np.zeros((3,3))
arr_zero_mxn

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arr_one_n = np.ones(9)
arr_one_n

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
arr_one_mxn = np.ones((3,3))
arr_one_mxn

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
arr_I = np.eye(5)
arr_I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
arr_I2 = np.identity(5)
arr_I2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 배열의 연산

In [9]:
arr1 = np.arange(1.0,7)
arr2 = np.arange(10.0,70,10)


print('arr1: %s \t shape:%s' % (repr(arr1), arr1.shape))
print('arr2: %s \t shape:%s' % (repr(arr2), arr2.shape))



arr1: array([1., 2., 3., 4., 5., 6.]) 	 shape:(6,)
arr2: array([10., 20., 30., 40., 50., 60.]) 	 shape:(6,)


### 배열의 덧셈

In [10]:
arr1 + 100

array([101., 102., 103., 104., 105., 106.])

In [11]:
arr1 + arr2

array([11., 22., 33., 44., 55., 66.])

### 배열의 뺄셈

In [12]:
arr1 - 5

array([-4., -3., -2., -1.,  0.,  1.])

In [13]:
arr1 - arr2

array([ -9., -18., -27., -36., -45., -54.])

### 배열의 곱셈

In [14]:
arr1 * 5

array([ 5., 10., 15., 20., 25., 30.])

In [15]:
arr1 * arr2

array([ 10.,  40.,  90., 160., 250., 360.])

### 배열의 나눗셈

In [16]:
arr1 / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        ])

In [17]:
arr1 / arr2

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

### 배열의 거듭제곱

In [18]:
arr1 ** 2

array([ 1.,  4.,  9., 16., 25., 36.])

In [19]:
arr1 ** arr2

array([1.00000000e+00, 1.04857600e+06, 2.05891132e+14, 1.20892582e+24,
       8.88178420e+34, 4.88736780e+46])

### 배열의 복합연산

In [20]:
(arr1 + 100) / arr2

array([10.1       ,  5.1       ,  3.43333333,  2.6       ,  2.1       ,
        1.76666667])

### 배열의 비교연산

In [21]:
arr2 > 20

array([False, False,  True,  True,  True,  True])

## 다차원 배열에서의 연산

In [22]:
arr1 = np.arange(1,9).reshape(2,4)

arr2 = np.arange(10,90,10).reshape(2,4)

print('arr1: %s \t\t shape:%s' % (repr(arr1), arr1.shape))
print('arr2: %s \t shape:%s' % (repr(arr2), arr2.shape))

arr1: array([[1, 2, 3, 4],
       [5, 6, 7, 8]]) 		 shape:(2, 4)
arr2: array([[10, 20, 30, 40],
       [50, 60, 70, 80]]) 	 shape:(2, 4)


In [23]:
arr1*arr2 

array([[ 10,  40,  90, 160],
       [250, 360, 490, 640]])

## 통계를 위한 연산

### sum - 합 / mean - 평균

In [32]:
arr1 = np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
arr1.sum()

66

In [37]:
arr1.sum(axis=0)

array([12, 15, 18, 21])

In [38]:
arr1.sum(axis=1)

array([ 6, 22, 38])

In [39]:
arr1.mean()

5.5

In [40]:
arr1.mean(axis=0)

array([4., 5., 6., 7.])

In [41]:
arr1.mean(axis=1)

array([1.5, 5.5, 9.5])

### std - 표준편차 / var - 분산

In [43]:
arr1.std()

3.452052529534663

In [44]:
arr1.var()

11.916666666666666

In [45]:
np.sqrt(arr1.var())

3.452052529534663

In [47]:
arr1.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [48]:
arr1.var(axis=0)

array([1.11803399, 1.11803399, 1.11803399])

In [56]:
np.sqrt(arr1.var(axis=0))

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [49]:
arr1.std(axis=1)

array([10.66666667, 10.66666667, 10.66666667, 10.66666667])

In [50]:
arr1.var(axis=1)

array([1.25, 1.25, 1.25])

In [57]:
np.sqrt(arr1.var(axis=1))

array([1.11803399, 1.11803399, 1.11803399])

### min - 최소값 / max - 최대값

In [59]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
arr1.min(), arr1.max()

(0, 11)

In [61]:
arr1.min(axis=0)

array([0, 1, 2, 3])

In [62]:
arr1.min(axis=1)

array([0, 4, 8])

In [63]:
arr1.max(axis=0)

array([ 8,  9, 10, 11])

In [64]:
arr1.max(axis=1)

array([ 3,  7, 11])

### cumsum - 누적합 / cumprod - 누적곱

In [71]:
arr1 +=1
arr1

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [72]:
arr1.cumsum()

array([ 2,  5,  9, 14, 20, 27, 35, 44, 54, 65, 77, 90])

In [73]:
arr1.cumsum(axis=0)

array([[ 2,  3,  4,  5],
       [ 8, 10, 12, 14],
       [18, 21, 24, 27]])

In [74]:
arr1.cumsum(axis=1)

array([[ 2,  5,  9, 14],
       [ 6, 13, 21, 30],
       [10, 21, 33, 46]])

In [75]:
arr1.cumprod()

array([         2,          6,         24,        120,        720,
             5040,      40320,     362880,    3628800,   39916800,
        479001600, 6227020800])

In [76]:
arr1.cumprod(axis=0)

array([[  2,   3,   4,   5],
       [ 12,  21,  32,  45],
       [120, 231, 384, 585]])

In [77]:
arr1.cumprod(axis=1)

array([[    2,     6,    24,   120],
       [    6,    42,   336,  3024],
       [   10,   110,  1320, 17160]])

## 행렬 연산

In [78]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(6, 0, -1).reshape(3, 2)

print("A: %s" % repr(A))
print("B: %s" % repr(B))

A: array([[1, 2, 3],
       [4, 5, 6]])
B: array([[6, 5],
       [4, 3],
       [2, 1]])


### 행렬곱

In [79]:
A.dot(B)

array([[20, 14],
       [56, 41]])

In [80]:
np.dot(A,B)

array([[20, 14],
       [56, 41]])

In [81]:
B.dot(A)

array([[26, 37, 48],
       [16, 23, 30],
       [ 6,  9, 12]])

In [82]:
np.dot(B,A)

array([[26, 37, 48],
       [16, 23, 30],
       [ 6,  9, 12]])

### 전치행렬

In [88]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
A.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [90]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [91]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [92]:
B

array([[6, 5],
       [4, 3],
       [2, 1]])

In [93]:
B.transpose()

array([[6, 4, 2],
       [5, 3, 1]])

In [94]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [95]:
np.transpose(B)

array([[6, 4, 2],
       [5, 3, 1]])

### 단위행렬

In [96]:
A = np.arange(1, 5).reshape(2, 2)
B = np.arange(4, 0, -1).reshape(2, 2)

print("A: %s" % repr(A))
print("B: %s" % repr(B))

A: array([[1, 2],
       [3, 4]])
B: array([[4, 3],
       [2, 1]])


In [97]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [98]:
A.dot(I)

array([[1., 2.],
       [3., 4.]])

In [99]:
B.dot(I)

array([[4., 3.],
       [2., 1.]])

### 역행렬

In [100]:
A

array([[1, 2],
       [3, 4]])

In [101]:
B

array([[4, 3],
       [2, 1]])

In [102]:
Ai = np.linalg.inv(A)
Ai

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [103]:
A.dot(Ai)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [104]:
Bi = np.linalg.inv(B)
Bi

array([[-0.5,  1.5],
       [ 1. , -2. ]])

In [105]:
B.dot(Bi)

array([[1., 0.],
       [0., 1.]])

### 행렬식

In [106]:
A

array([[1, 2],
       [3, 4]])

In [107]:
np.linalg.det(A)

-2.0000000000000004

In [108]:
np.linalg.det(B)

-2.0

# 배열의 인덱싱과 슬라이싱

In [109]:
arr1 = np.arange(0, 60, 10)
arr1

array([ 0, 10, 20, 30, 40, 50])

In [110]:
print(arr1[0])
print(arr1[1])
print(arr1[-1])

0
10
50


In [112]:
arr1[:4]

array([ 0, 10, 20, 30])

In [113]:
arr1[3:]

array([30, 40, 50])

In [114]:
arr1[::2]

array([ 0, 20, 40])

In [115]:
arr1[1] = 100
arr1

array([  0, 100,  20,  30,  40,  50])

In [117]:
arr1[[1,4]] # 1과 4 인덱스 가져오기

array([100,  40])

### 2차원 배열 인덱싱 슬라이싱

In [118]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [120]:
arr1[1] # 1행 가져오기

array([3, 4, 5])

In [121]:
arr1[1][1] # 1행 1열 가져오기

4

In [122]:
arr1[1][1] = 30
arr1

array([[ 0,  1,  2],
       [ 3, 30,  5],
       [ 6,  7,  8]])

In [125]:
arr1[0,2] # 0행 2열

2

In [126]:
arr1[0,2] = 10
arr1

array([[ 0,  1, 10],
       [ 3, 30,  5],
       [ 6,  7,  8]])

In [128]:
arr1[2] = [3,3,3] # 열 전체 변경
arr1

array([[ 0,  1, 10],
       [ 3, 30,  5],
       [ 3,  3,  3]])

In [130]:
arr1[1:,1:] 

array([[30,  5],
       [ 3,  3]])

In [131]:
arr1[1:,1:] = np.array([[1,2],[3,4]])
arr1

array([[ 0,  1, 10],
       [ 3,  1,  2],
       [ 3,  3,  4]])

### 조건으로 인덱싱 슬라이싱

In [132]:
arr1 = np.arange(10,100,10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [134]:
arr1>50

array([False, False, False, False, False,  True,  True,  True,  True])

In [135]:
arr1[arr1>50]

array([60, 70, 80, 90])

In [136]:
arr2 = np.arange(10,100,10).reshape(3, 3)
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [138]:
arr2%4 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [139]:
arr2[arr2%4 == 0]

array([20, 40, 60, 80])

## NaN (not a number) & Inf(Infinity)

In [141]:
import numpy as np

In [142]:
np.nan

arr1 = np.array([1,2,3, np.nan, np.inf, -np.inf])
arr1


array([  1.,   2.,   3.,  nan,  inf, -inf])

# 다차원 연습하기

In [147]:
m = np.arange(18).reshape(3,2,3)

In [148]:
m

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [149]:
m[0,1,2]

5

In [151]:
m[2,1,1]

16

In [153]:
m[:,1,:]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17]])

In [154]:
m[2,:,:]

array([[12, 13, 14],
       [15, 16, 17]])

In [155]:
m[2,...]

array([[12, 13, 14],
       [15, 16, 17]])

In [157]:
m[...,1]

array([[ 1,  4],
       [ 7, 10],
       [13, 16]])

In [160]:
m

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [161]:
for i in m:
    print(i)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[12 13 14]
 [15 16 17]]


In [165]:
# m.flat: 차원을 펼쳐라.
for i in m.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


In [166]:
m.shape

(3, 2, 3)

In [167]:
# error가 됨.
m.reshape(2, 4) 

ValueError: cannot reshape array of size 18 into shape (2,4)

In [170]:
m.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [174]:
m.reshape(6,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [177]:
# 자체가 바뀜. == m.shape= 3,6
m.resize(3, 6)

In [181]:
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [183]:
m.shape= (3,6)

In [184]:
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

### vstack

In [187]:
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [191]:
# 아래로 스택을 쌓음
# verstical stack
np.vstack((m,m)) 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [204]:
a = np.vstack((m, m, m))

In [205]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [217]:
i,j,k = np.vsplit(a, 3)

In [218]:
i

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [219]:
j

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [220]:
k

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [200]:
np.hstack((m, m))

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17]])

In [221]:
b = np.hstack((m, m, m))

In [222]:
b

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5,  0,  1,  2,  3,
         4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11,  6,  7,  8,  9,
        10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17, 12, 13, 14, 15,
        16, 17]])

In [224]:
i, j, k = np.hsplit(b, 3)

In [225]:
i

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [226]:
j

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [227]:
k

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [228]:
i == j

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [230]:
i is j # 완전이 같냐 = 주소까지 같냐

False

In [231]:
id(i)

4677413584

In [232]:
id(j)

4677413664

In [238]:
a = np.arange(10)

In [239]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [240]:
b = [x*2 for x in a if x % 2 == 0 ]

In [241]:
b

[0, 4, 8, 12, 16]

In [212]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '