# Bagging

In [1]:
import os
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import graphviz # pip install 

In [2]:
DATASET_DIR = os.path.join(os.path.dirname(os.getcwd()), 'datasets')

In [3]:
red_file = os.path.join(DATASET_DIR, 'winequality-red.csv')
white_file = os.path.join(DATASET_DIR, 'winequality-white.csv')

In [4]:
wine_red = pd.read_csv(red_file, sep=';')
wine_white = pd.read_csv(white_file, sep=';')

In [5]:
wine_red.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [6]:
wine_white.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [7]:
len(wine_red), len(wine_white)

(1599, 4898)

In [8]:
wine_red.head()

wine_white.head()

len(wine_red), len(wine_white)

(1599, 4898)

In [103]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

### 1. Feature_n: 2(volatile acidity, sulphates), Binary Problem

In [9]:
new_red = wine_red.copy()
new_red['is_red'] = 1
new_white = wine_white.copy()
new_white['is_red'] = 0

wine = new_red.append(new_white, ignore_index=True)


In [10]:
wine.head(2)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70          0.0             1.9      0.076   
1            7.8              0.88          0.0             2.6      0.098   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   

   alcohol  quality  is_red  
0      9.4        5       1  
1      9.8        5       1

In [11]:
wine.tail(2)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  is_red  
6495     12.8        7       0  
6496     11.8        6       0

In [12]:
X = wine.drop('quality', axis=1)
y = wine['quality']

##### split train&test

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
train_X, test_X, train_y, test_y = train_test_split(X, y, stratify=wine['is_red'], random_state=42)

In [37]:
from sklearn.ensemble import RandomForestClassifier
"""
RandomForestClassifier(n_estimators=’warn’, criterion=’gini’, max_depth=None, 
                       min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
                        max_features=’auto’, max_leaf_nodes=None, min_impurity_decrease=0.0, 
                        min_impurity_split=None, bootstrap=True, oob_score=False, n_jobs=None, 
                        random_state=None, verbose=0, warm_start=False, class_weight=None)
                        
# n_estimators : integer, optional (default=10)
- The number of trees in the forest.

# criterion : string, optional (default=”gini”)
- The function to measure the quality of a split. 
- Supported criteria are “gini” for the Gini impurity and “entropy” for the information gain. 
Note: this parameter is tree-specific

# max_depth: 
# max_features: 
# max_leaf_nodes:
# ... (decision Tree 상속)

# bootstrap : boolean, optional (default=True)
        Whether bootstrap samples are used when building trees. If False, the
        whole datset is used to build each tree.
        
# oob_score : bool (default=False)
        Whether to use out-of-bag samples to estimate
        the generalization accuracy.
"""
clf =  RandomForestClassifier(10, criterion='entropy', random_state=0,
                              max_features='auto')
clf.fit(train_X, train_y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=5, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [38]:
clf.score(train_X, train_y)

0.9850164203612479

In [39]:
clf.score(test_X, test_y)

0.6535384615384615

In [40]:
clf.max_features

5

In [41]:
clf.n_features_

12

##### attribute

In [24]:
# list of DecisionTreeClassifier
clf.estimators_

[DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                        max_features='auto', max_leaf_nodes=None,
                        min_impurity_decrease=0.0, min_impurity_split=None,
                        min_samples_leaf=1, min_samples_split=2,
                        min_weight_fraction_leaf=0.0, presort=False,
                        random_state=209652396, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                        max_features='auto', max_leaf_nodes=None,
                        min_impurity_decrease=0.0, min_impurity_split=None,
                        min_samples_leaf=1, min_samples_split=2,
                        min_weight_fraction_leaf=0.0, presort=False,
                        random_state=398764591, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                        max_features='auto', max_leaf_nodes=None,
          

In [42]:
clf.predict_proba(test_X)

array([[0. , 0. , 0.3, 0.7, 0. , 0. ],
       [0.3, 0. , 0.2, 0.4, 0.1, 0. ],
       [0. , 0.2, 0.3, 0.4, 0.1, 0. ],
       ...,
       [0. , 0.1, 0. , 0.3, 0.3, 0.3],
       [0. , 0. , 1. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 1. , 0. , 0. ]])

In [43]:
clf.classes_

array([3, 4, 5, 6, 7, 8], dtype=int64)

In [44]:
# The number of features when fit is performed.
clf.n_features_

12

In [45]:
X.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'is_red'],
      dtype='object')

In [28]:
clf.feature_importances_

array([0.07111784, 0.09794398, 0.0796715 , 0.08526031, 0.08706186,
       0.09345741, 0.08783301, 0.10536196, 0.07875339, 0.08203306,
       0.12765338, 0.0038523 ])

In [90]:
# Score of the training dataset obtained using an out-of-bag estimate.
clf.oob_score

False

In [91]:
clf.predict(test_X)

array([0, 0, 0, ..., 0, 0, 0])

In [92]:
clf.predict_proba(test_X)

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [93]:
clf.score(train_X, train_y)

0.958743842364532

In [94]:
clf.score(test_X, test_y)

0.8929230769230769

# Quality

In [113]:
new_red = wine_red.copy()
new_white = wine_white.copy()


In [114]:
X = new_red.drop('quality', axis=1)
y = new_red['quality']

In [115]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, stratify=y, random_state=42, test_size=.2)


In [116]:
train_y.head()

1542    6
1558    5
344     6
924     5
971     6
Name: quality, dtype: int64

In [131]:
clf =  RandomForestClassifier(5000, criterion='entropy', random_state=0, max_features='sqrt')
clf.fit(train_X, train_y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='sqrt', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [132]:
clf.score(train_X, train_y)

1.0

In [133]:
clf.score(test_X, test_y)

0.69375

# Grid Search

In [ ]:
"""
GridSearchCV(estimator, param_grid, scoring=None, n_jobs=None, iid=’warn’, refit=True, cv=’warn’, 
             verbose=0, pre_dispatch=‘2*n_jobs’, error_score=’raise-deprecating’, return_train_score=False)

Exhaustive search over specified parameter values for an estimator.

Important members are fit, predict.

GridSearchCV implements a “fit” and a “score” method. It also implements “predict”, “predict_proba”, “decision_function”, “transform” and “inverse_transform” if they are implemented in the estimator used.

The parameters of the estimator used to apply these methods are optimized by cross-validated grid-search over a parameter grid.


"""

""

In [56]:
# feature_len/3
from sklearn.model_selection import GridSearchCV

clf = RandomForestClassifier(random_state=42)

# param_grid = { 
#     'n_estimators': [200, 400, 600, 800],
#     'max_features': ['sqrt', 'log2'],
#     'max_depth' : [20, 25, 30, 40],
#     'criterion' :['gini', 'entropy']
# }

param_grid = { 
    'n_estimators': [400, 600],
    'max_features': ['sqrt'],
    'max_depth' : [25, 30, 40],
    'criterion' :['entropy']
}

CV_clf = GridSearchCV(estimator=clf, param_grid=param_grid, cv= 5)


CV_clf.fit(train_X, train_y)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False, random_state=42,
                                              verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'

In [59]:
CV_clf.best_estimator_

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=30, max_features='sqrt', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=600,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [60]:
CV_clf.score(test_X, test_y)

0.6812307692307692

In [52]:
CV_clf.cv_results_

{'mean_fit_time': array([0.40042286, 0.78944521, 0.39522252, 0.79144535, 0.45242581,
        0.90125151, 0.45282593, 0.91565232, 0.49402833, 0.98745642,
        0.49402823, 0.98745656, 0.52422991, 1.0416595 , 0.52142982,
        1.04305964, 0.53603063, 1.06766119, 0.53383055, 1.06746097,
        0.54103084, 1.07666173, 0.53843079, 1.07506142, 0.63643646,
        1.27227273, 0.63703642, 1.28447328, 0.74084234, 1.48628502,
        0.74084234, 1.48168478, 0.80784626, 1.6070919 , 0.80464602,
        1.60889192, 0.83724785, 1.68469629, 0.83724794, 1.67829595,
        0.85644894, 1.70709767, 0.85704904, 1.70589752, 0.85644898,
        1.71589823, 0.85604897, 1.71969833]),
 'std_fit_time': array([0.00688806, 0.00338243, 0.00636904, 0.00480035, 0.00135645,
        0.00231539, 0.00305954, 0.02870437, 0.0032865 , 0.00422396,
        0.00141435, 0.00162496, 0.00534431, 0.00195978, 0.00215415,
        0.00509937, 0.00586543, 0.00280016, 0.00172055, 0.00823692,
        0.00635658, 0.00463076, 0.002