# Bagging

In [95]:
import os
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import graphviz # pip install 



In [96]:
DATASET_DIR = os.path.join(os.path.dirname(os.getcwd()), 'datasets')

In [97]:
red_file = os.path.join(DATASET_DIR, 'wine/winequality-red.csv')
white_file = os.path.join(DATASET_DIR, 'wine/winequality-white.csv')

In [98]:
wine_red = pd.read_csv(red_file, sep=';')
wine_white = pd.read_csv(white_file, sep=';')

In [99]:
wine_red.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [100]:
wine_white.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [101]:
len(wine_red), len(wine_white)

(1599, 4898)

In [102]:
wine_red.head()

wine_white.head()

len(wine_red), len(wine_white)

(1599, 4898)

In [103]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

### 1. Feature_n: 2(volatile acidity, sulphates), Binary Problem

In [104]:
new_red = wine_red.copy()
new_red['is_red'] = 1
new_white = wine_white.copy()
new_white['is_red'] = 0

wine = new_red.append(new_white, ignore_index=True)


In [105]:
wine.head(2)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70          0.0             1.9      0.076   
1            7.8              0.88          0.0             2.6      0.098   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   

   alcohol  quality  is_red  
0      9.4        5       1  
1      9.8        5       1

In [106]:
wine.tail(2)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  is_red  
6495     12.8        7       0  
6496     11.8        6       0

In [107]:
X = wine[['volatile acidity', 'sulphates']]
y = wine['is_red']

##### split train&test

In [108]:
from sklearn.model_selection import train_test_split

In [109]:
train_X, test_X, train_y, test_y = train_test_split(X, y, stratify=wine['is_red'], random_state=42)

In [110]:
from sklearn.ensemble import RandomForestClassifier
"""
RandomForestClassifier(n_estimators=’warn’, criterion=’gini’, max_depth=None, 
                       min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
                        max_features=’auto’, max_leaf_nodes=None, min_impurity_decrease=0.0, 
                        min_impurity_split=None, bootstrap=True, oob_score=False, n_jobs=None, 
                        random_state=None, verbose=0, warm_start=False, class_weight=None)
                        
# n_estimators : integer, optional (default=10)
- The number of trees in the forest.

# criterion : string, optional (default=”gini”)
- The function to measure the quality of a split. 
- Supported criteria are “gini” for the Gini impurity and “entropy” for the information gain. 
Note: this parameter is tree-specific

# max-depth: 
# max_features: 
# max_leaf_nodes:
# ... (decision Tree 상속)

# bootstrap : boolean, optional (default=True)
        Whether bootstrap samples are used when building trees. If False, the
        whole datset is used to build each tree.
        
# oob_score : bool (default=False)
        Whether to use out-of-bag samples to estimate
        the generalization accuracy.
"""
clf =  RandomForestClassifier(10, criterion='entropy', random_state=0)
clf.fit(train_X, train_y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [111]:
clf.score(train_X, train_y)

0.958743842364532

In [112]:
clf.score(test_X, test_y)

0.8929230769230769

##### attribute

In [86]:
# list of DecisionTreeClassifier
clf.estimators_

[DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                        max_features='auto', max_leaf_nodes=None,
                        min_impurity_decrease=0.0, min_impurity_split=None,
                        min_samples_leaf=1, min_samples_split=2,
                        min_weight_fraction_leaf=0.0, presort=False,
                        random_state=209652396, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                        max_features='auto', max_leaf_nodes=None,
                        min_impurity_decrease=0.0, min_impurity_split=None,
                        min_samples_leaf=1, min_samples_split=2,
                        min_weight_fraction_leaf=0.0, presort=False,
                        random_state=398764591, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                        max_features='auto', max_leaf_nodes=None,
          

In [87]:
clf.classes_

array([0, 1])

In [88]:
# The number of features when fit is performed.
clf.n_features_

2

In [89]:
clf.feature_importances_

array([0.59069184, 0.40930816])

In [90]:
# Score of the training dataset obtained using an out-of-bag estimate.
clf.oob_score

False

In [91]:
clf.predict(test_X)

array([0, 0, 0, ..., 0, 0, 0])

In [92]:
clf.predict_proba(test_X)

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [93]:
clf.score(train_X, train_y)

0.958743842364532

In [94]:
clf.score(test_X, test_y)

0.8929230769230769

# Quality

In [113]:
new_red = wine_red.copy()
new_white = wine_white.copy()


In [114]:
X = new_red.drop('quality', axis=1)
y = new_red['quality']

In [115]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, stratify=y, random_state=42, test_size=.2)


In [116]:
train_y.head()

1542    6
1558    5
344     6
924     5
971     6
Name: quality, dtype: int64

In [131]:
clf =  RandomForestClassifier(5000, criterion='entropy', random_state=0, max_features='sqrt')
clf.fit(train_X, train_y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='sqrt', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [132]:
clf.score(train_X, train_y)

1.0

In [133]:
clf.score(test_X, test_y)

0.69375

# Grid Search

In [ ]:
"""
GridSearchCV(estimator, param_grid, scoring=None, n_jobs=None, iid=’warn’, refit=True, cv=’warn’, 
             verbose=0, pre_dispatch=‘2*n_jobs’, error_score=’raise-deprecating’, return_train_score=False)

Exhaustive search over specified parameter values for an estimator.

Important members are fit, predict.

GridSearchCV implements a “fit” and a “score” method. It also implements “predict”, “predict_proba”, “decision_function”, “transform” and “inverse_transform” if they are implemented in the estimator used.

The parameters of the estimator used to apply these methods are optimized by cross-validated grid-search over a parameter grid.


"""

""

In [ ]:
# feature_len/3
from sklearn.model_selection import GridSearchCV
CV_clf = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
param_grid = { 
    'n_estimators': [200, 500, 800, 1000],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [10, 12, 14, 16, 18, 20],
    'criterion' :['gini', 'entropy']
}
CV_clf.fit(x_train, y_train)