In [1]:
import numpy as np

In [4]:
a = np.arange(22)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [20]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [5]:
b = a.reshape(2,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]])

In [19]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]])

In [6]:
a.shape

(22,)

In [7]:
b.shape

(2, 11)

In [8]:
a.ndim

1

In [9]:
b.ndim

2

In [10]:
a.dtype.name

'int64'

In [11]:
b.dtype.name

'int64'

In [12]:
type(a)

numpy.ndarray

In [25]:
# 타입 변환
c = np.array([(1,2,3), (4,5.5,6)])

In [26]:
c

array([[1. , 2. , 3. ],
       [4. , 5.5, 6. ]])

In [27]:
c.dtype

dtype('float64')

In [28]:
# 타입 강제
d = np.array([(1,2,3), (4,5.5,6)], dtype=int)

In [29]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
# 어떤 모양을 어떤걸로 채워라
np.full((3,3), 555.5)

array([[555.5, 555.5, 555.5],
       [555.5, 555.5, 555.5],
       [555.5, 555.5, 555.5]])

In [35]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [36]:
# 시작점과 끝점에서 11개를 뽑아내라
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [39]:
e = np.array([1, 2, 3, 4])

In [40]:
e

array([1, 2, 3, 4])

In [41]:
f = np.arange(4)

In [42]:
f

array([0, 1, 2, 3])

In [44]:
e+f

array([1, 3, 5, 7])

In [45]:
e-f

array([1, 1, 1, 1])

In [46]:
e*f

array([ 0,  2,  6, 12])

In [49]:
e/3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [50]:
e**4

array([  1,  16,  81, 256])

In [ ]:
g = np.arange()